### ISSUE TITLE
Dragon Hide both version did not change with the additions of new Fizban Dragonborns

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1073]
I added type dragonborn to the old Dragonborn race and changed the pick req to ttDragonbor. Claw was off a bit so readded as Unarmed strike with name of Claw. Here's the code
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/8954379/custom.txt)
.

**Comment by Fenris447** [comment]
Because the base Dragonborn are part of the SRD, it takes a _ton_ of work to replace them within the pack. It's been done before with the Tieflings, but that's a huge headache and not one that's really worth doing just for this.

The workaround is to make the requisite look for _either_ the base Dragonborn race _or_ the Dragonborn type. This is already in place for the XGTE version of Dragon Hide, but I'll apply it to the UA version. I'm doing the same for Dragon Wings. And it also tells me I need to do a full review for all the subraces added in MPMotM and later as well for pre-requisites. That's a headache, but one I'll take on.

Can you explain what problems you had with the Claw?

**Comment by Fenris447** [comment]
Oh I think I get what was wrong with the Claw. I have it the IsWeapon.wUnarmed tag so that it functions like similar features, such as the Tabaxi's Claws.

I finished reviewing and updating every Feat I could find to make they would work both for the base race and the new variations of the races (like MPMotM Eladrin, AAG Astral Elf, etc.). Thanks for putting this all on my radar. It was a good and necessary thing to review!
