### ISSUE TITLE
Cranium Rat wildshape min5CCraRa

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1081]
Selecting this result in a blank race. No stats at all. I looked at the race r5CVGMCran in the minion gizmo and it seem normal. I tried the other cranium rat r5CCraRatR and it work fine now. That went into the minion gizmo.

**Comment by Fenris447** [comment]
This is occurring because selecting MPMotM precludes out the VGM Cranium Rat; it's a Beast in VGM but an Aberration in MPMotM. So when you try to get the wild shape of the VGM version, it can't find the VGM version due to the preclude. I've added the Cranium Rat wild shape to the preclude list when MPMotM is selected. I'll do the same for the Stench Kow.
