### ISSUE TITLE
Procedure S2SetName throwing a warning

### ISSUE THREAD

**Issue by CaptCalamitous** [Sklore/HL_DD_5e_Colab#1105]
Any update I have on  a portfolio with a specific character in it generates a warning.

This occurs twice when trying to print the hero.

![HeroLabError](https://user-images.githubusercontent.com/94298701/194093436-3a92e83e-9eef-4042-af79-ff151aa93fa5.jpg)

I am on the latest Community pack, using Hero Lab on Windows 10.

**Comment by Fenris447** [comment]
Can you upload the .por file?

**Comment by CaptCalamitous** [comment]
Thanks for the help, here it is.
I did wonder if one of the character names might have caused it, the name had a single ' in it, but I removed that and the result was the same.

[Nok the Maker_rolled.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/9719372/Nok.the.Maker_rolled.zip)

**Comment by CaptCalamitous** [comment]
Sorry total noob with Github.

**Comment by Fenris447** [comment]
Okay I figured it out! The problem is the "Custom Name: Race" adjustment you're using. To try and make it as simple as possible, it's using that S2SetName procedure to change the race's name. That same procedure is used for changing the names of weapons, spells, etc. with their respective custom name/custom text adjustments. Except Races (apparently) don't have the sbName field, unlike all those other things. So when the procedure says "change the sbName field", Hero Lab gets mad because races don't have that field.

So I've made a new procedure (without the sbName part) specifically for custom naming races and updated the two relevant adjustments to use that new procedure.

It's going to be a few months until the next patch. But if you want the fixed stuff in the mean time, download the attached two files and add them to your ProgramData\Hero Lab\data\5e folder. It'll need to override the older versions of these files.

[Custom Name Fixes.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/9904247/Custom.Name.Fixes.zip)
