### ISSUE TITLE
Tiefling Racial spells

### ISSUE THREAD

**Issue by ranmadavies** [Sklore/HL_DD_5e_Colab#117]
while Thaumaturgy works and darkness works at level 5, at level 3, I'm supposed to get Hellish Rebuke once per long rest as a second level spell.

**Comment by grandchefpanda** [comment]
Hellish Rebuke is not in the SRD, but the tiefling is.

**Comment by Sklore** [comment]
I can fix this but I would love @shadowchemosh thoughts on how I have done it. 

I had to create a copy of LWs Tiefling (rTiefling) and LWs Infernal Legacy (raTiLegacy). I've added the spell to the new Infernal Legacy (ra5CInfLeg) which I've linked to the new Tiefling (r5CTieflin). 

I've added rTiefling and raTiLegacy to Deprecated Things as Hidden objects. 

Acceptable?

**Comment by MortierC** [comment]
This is GrandChefPanda :-)
that was my idea too but the solution will give problems if there is a bug corrected or a change in the thiefling race done officially, the copy will keep the bug.

**Comment by Sklore** [comment]
I've made the changes in my branch pending @shadowchemosh's wealth of experience :dango:

**Comment by shadowchemosh** [comment]
Looking...  This is a different problem.  Normally in other systems we would have LW fix any "core" feature like this.  But in this case they can't because the spell does not exist.

What GrandChefPanda is saying is "true" but races don't often have many fixes to them.  At least in what I have seen that is classes that get 99% of the fixes.

On the good side it does mean it gives the community "full" control over the Tiefling race to make any other fixes or enhancements needed as the 5e progresses onward.  Usually in the idea of new books and new features.

A "third" option to fix this is by using the mechanic that is in the helper file.  The mechanic is always live on all characters and it could be setup to add the spell for the racial ability instead. This allows the spell to appear only for the those with the correct Racial Ability and character level.  But we don't modify any existing "things". On the mechanic you would do the following bootstrap:
```
    <bootstrap thing="sp5CHelliR">
      <containerreq phase="First" priority="2500"><![CDATA[Ability.raTiLegacy & !AbReplace.raTiLegacy & (count:Classes.? >= 3)]]></containerreq>
      <autotag group="Helper" tag="RaceSpell"/>
      <autotag group="Usage" tag="Day"/>
      <assignval field="trkMax" value="1"/>
      </bootstrap>
```
The logic above says I have to have the "Infernal Legacy" racial special and it has NOT been replaced by something else and I am level 3 or higher.

**Comment by Sklore** [comment]
Will be fixed in next release. 

Went with the hidden option.

**Comment by shadowchemosh** [comment]
@Sklore thinking about this I think we (me) would like to do small change. I think we should go with "Preclude" instead of HIDDEN in this case and source mark our Tiefling to 5e Community.  This would then allow for the LW Teifling to be be seen until you activate the 5e Community source and then it would be hidden and we would display "our" verison.

I am a little against "always" hiding the race on people just encase they want to go backwards.

Last thought is that we need to add two scripts that will push the "Race.rTeifling" tag to the hero and the HasAbility.raTiLegacy tags to the hero.  These are the tags that the macros #hasrace[] and #hasability[] use to test for the presence of races/abilities.  This way you could still test for the #hasrace[rTeifling] tag and our stuff, LW stuff, and custom stuff would still meet any pre-reqs.  

I know no feats or stuff do race pre-req's but its a common pre-req that later books could add.

**Comment by Sklore** [comment]
It's its the better way to go i'm fully supportive.

**Comment by shadowchemosh** [comment]
Ok great.  It won't take me long at all to do tonight.  I will make that change just before the new release then.

Thanks!
