### ISSUE TITLE
Shadow Warrior

### ISSUE THREAD

**Issue by xdy** [Sklore/HL_DD_5e_Colab#197]
**STATUS:** Incomplete

**OUTSTANDING:**
- Exotic weapon training
- Cantrips: You gain the minor illusion cantrip, and two additional cantrips from the following list: blade ward, chill touch, dancing lights, friends, mage hand, message, shadow whip*, or true strike. At 10th level, you may choose one additional cantrip from the above list."

Hi,
A fairly complete Shadow Warrior (from Rogue Genius Games, http://www.drivethrurpg.com/product/167621/5e-Options-Rogue-Archetypes--Shadow-Warrior) is included in this issue.
I _think_ the only things missing are Sources and Product Identity, as I couldn't figure out how to do them.
All text is paraphrased, so hopefully ok.

((Removed old file))

**Comment by shadowchemosh** [comment]
For 3PP you could maybe include the full text.  You have to check the copyright 15 section that covers Product Identity information.  If nothing is listed then you can include the full text as is.  Many 3PP companions like RGG don't do allot of Product Identity actually.

**Comment by xdy** [comment]
You're probably right given that the PI and OC sections are:
"DESIGNATION OF PRODUCT IDENTITY:
The Rogue Genius Games (RGG) company name and logo; the “Genius Guide to the Shadow Warrior” name and logo; all artwork, backgrounds, and logos; all trade dress, and graphic design elements.
DECLARATION  OF  OPEN  CONTENT:
All game mechanics, proper names of classes, prestige classes, archetypes, feats, skills, spells,
magic items, monsters, rituals, artifacts AND OR the names of abilities presented within this book
are Open Game Content as described in Section 1(d) of the License."

So, nothing should need to be flagged as Product Identity, but how should I handle section 15? (See below, starts with the usual preamble, but it also includes a dependence on a 3e book.)

"15 COPYRIGHT NOTICE
Open Game License v 1.0a, © 2000, Wizards of the Coast, Inc.
System Reference Document, © 2000, Wizards of the Coast, Inc.; Authors Jonathan Tweet,
Monte Cook, Skip Williams, based on material by E. Gary Gygax and Dave ArnesonSkreyn’s Register: The Bonds of Magic. © 2002, Sean K Reynolds
5e Options: Rogue Archetypes Shadow Warrior. ©2015, Rogue Genius Games. Designers:
Owen K.C. Stephens and Rich E. Howard."

I used to be quite involved in pcgen several years ago (number two name in the 'Code monkey's section of the about box :), and though I mostly coded, I did do enough lst-files that I knew how to do things for pcgen (see below), but I don't know how you handle things.
Quoting from http://www.pcgen.org/autobuilds/pcgen-docs/listfilepages/listfileLSTstandards.html
"Copyright (in PCC)
ONLY and EXACTLY what is in the Sec. 15 of the OGL. VERBATIM.
If there are Typos, leave them in.  Weird characters, leave them in.  Stupid comments, leave them in.
Including a scanned page from the book with your submission would be nice but not completely necessary."

**Comment by shadowchemosh** [comment]
Based on the above you are free to fully copy in the text into HL for this class.  You don't need to be as "exact" as that PCGen comment.  I would format the text to look nice in HL including making things bold and spell names italics etc...

If things have misspelling I would fix them if you notice.  This is what we do in Pathfinder anyways.

I went ahead and added a new Parent for RGG and specifically this book to GitHub.

**Comment by xdy** [comment]
Well, you done this a lot more than I have, so you're probably right.
I've attached an updated file to this post (and will remove the one above), hopefully everything's done right.

[JK_5CSW.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/172389/JK_5CSW.zip)

**Comment by shadowchemosh** [comment]
Cool thanks!  I will merge this in as soon as I can.

**Comment by Sklore** [comment]
@shadowchemosh you might be able to do something with Exotic Weapon Training.

**Comment by xdy** [comment]
Just remembered that I couldn't figure out how to do the cantrips, the text is:
"Cantrips. You gain the minor illusion cantrip, and two additional cantrips from the following list: blade ward, chill touch, dancing lights, friends, mage hand, message, shadow whip*, or true strike. At 10th level, you may choose one additional cantrip from the above list."

I tried mucking about with code inspired (i.e. blatantly ripped off from) Magic Initiate, but, I obviously didn't know what I was doing, so backed out of that.
Any suggestions?

**Comment by LordMorin** [comment]
Once I finish up with what I am doign for Elemental Evil, I'll take a look at what I did for SCAG and the Arcane domain.  I know I came up with something that seemed to work (I think). :)

**Comment by shadowchemosh** [comment]
@Sklore thanks!  I was going to get to that today actually.  Well I hope.  Its finally the weekend here for me.  You know living in the past. =)  Yeah I need to re-read that Exotic weapon training thing a few more times to get my head around the "rules".

**Comment by LordMorin** [comment]
Here is what I have do so far for SCAG.
Arcane domain, Tiefling variant & traits.

Warning: Some of the Tiefling traits (Cateyes, 6 fingers, ect. have been house ruled so you may want to make them conform to the SCAG rules).

[soe_5e_scag.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/181019/soe_5e_scag.zip)

**Comment by grandchefpanda** [comment]
Will integrate Arcane domain tomorrow

**Comment by TheEnthusiast** [comment]
@xdy,

Hi,

I suppose you are working on this? I'm going to help with the cantrip stuff. So:

- The first item in the description says that we gain Minor Illusion. To do this, we add a new bootstrap:
1) Bootstrap spMinoIllu 
2) Add the following tags to the bootstrap (click on the Tags, to the right): Helper.Free, SpellType.cHelpRog, portal.ClsSplCant

This will show the Minor Illusion cantrip as a free cantrip in the spell list.

- The following item says you receive 2 cantrips from a specific list, plus an additional one at 10th level. To do That:

1) Open the Shadow Warrior (c5CShaWar) in the Editor and click the Eval Scripts button.
2) Locate these lines:
        ~ Cantrip Array
        focus.field[cArrKnCan].arrayvalue[2] += 3
        focus.field[cArrKnCan].arrayvalue[10] += 1
And change them to:
        ~ Cantrip Array
        focus.field[cArrKnCan].arrayvalue[2] += 2
        focus.field[cArrKnCan].arrayvalue[9] += 1

This will add the correct number of cantrips at the correct levels. Remember that the level array starts at 0 to designate the first level.

The last thing missing is to restrict the cantrips. To do that, you need to manipulate the field cCnKnoExpr of the class helper object, cHelpRog. Every class has a helper by the name cHelpXXX where XXX is the class identifier. The fields there control several aspects of the spell lists available to the class. cCnKnoExpr  itself is a tag expression that selects the cantrips available for selection. The final spell evaluation is done at Final Phase, priority 20000. So we need to edit the field after that. We create yet another eval script on c5CShaWar, with the following content:

Phase: Final Phase
Priority: 21000
Index: 2 (doesn't really matter).

Script:

hero.childfound[cHelpRog].field[cCnKnoExpr].text = "( DescInfo.sp5CSWCSW | DescInfo.sp5CBladeW | DescInfo.spChilTouc | DescInfo.spDancLigh | DescInfo.sp5CFriend | DescInfo.spMageHand | DescInfo.spMessage | DescInfo.spTrueStri ) & sLevel.0"

Since we have to pick individual spells, I modify the tag expression by usingf the DescInfo. group followed by the spell's unique identifier. With all of these changes in place, you have the cantrip selection working properly.

I'm not commiting this to the three, I don't know if you are working on a newer version of the file or not.

Let me know if you have questions.

**Comment by Sklore** [comment]
I've not started this. Just managed to read the pdf before I was called away the last time I tried.

**Comment by Sklore** [comment]
Cantrips Completed
