### ISSUE TITLE
IPAD

### ISSUE THREAD

**Issue by ghaleonausa** [Sklore/HL_DD_5e_Colab#205]
having a tough time getting the community pack to work on my ipad, i followed the instructions for custom source, found pack, downloaded. it just wont show in existing portfolios or new ones, please advise

**Comment by shadowchemosh** [comment]
http://forums.wolflair.com/showpost.php?p=226168&postcount=103

As I posted in the forums I simply need "more" information to help you. 

What part are you stuck on? Did you get the download onto the iPad? Did you get the URL entered? Are you in 5e and not Pathfinder game system? Are you getting any errors?

Pictures are always great so that we can see what you see...

**Comment by HippyCraig** [comment]
ghaleonausa, are you still having an issue with the iPad?  I have tested it on mine and its working fine. As shadow said, if you can send some screenshots it would help.

**Comment by Sklore** [comment]
Closing due to no response from client.
