### ISSUE TITLE
Feat: Duel Wielder - Error

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#212]
for the Duel Wielder feat, your script appears to be assigning the wrong version of the tag. Helper.TwoWpLight is meant to be assigned to weapons to exempt them from the "off hand weapon must be light" rule. Since you want to exempt all such weapons, you are correctly working in the hero context, but in that case, you need to assign Hero.TwoWpLight.

**Comment by shadowchemosh** [comment]
LOL I read the forums.  I saw this and posted about the confusion as Aaron originally did say Helper not Hero. =)

**Comment by Sklore** [comment]
From what i can tell this should just stop the error saying the character is wielding weapons they shouldn't be. That's the issue we occurred in game.

**Comment by shadowchemosh** [comment]
Correct that was the bug I reported to LW.  Because Aaron said in
http://forums.wolflair.com/showthread.php?p=224593&highlight=TwoWpLight#post224593

He would make that happen with Helper.TwoWpLight.  But I missed when they officially added 1.2 they changed it to Hero.TwoWpLight.  This is also covered in issue #139 Topic.
