### ISSUE TITLE
Implementing the faery dragon

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#216]
Ok, there is 7 types of Faery Dragons with different colors, each color has different inner casting spells and depending of the spell the CR is different (1 or 2).
There is 2 ways to implement this:
1) make 7 races, but the color is in fact depending of the age of the faery dragon.
2) make 1 race, have an option to let the user select the color and adjust the spells and CR depending of it.
I can do the first option without problem but I will need a lot of help to do the better 2nd option. Can someone help scripting this ?

**Comment by Sklore** [comment]
Way beyond my skill level sorry.

**Comment by shadowchemosh** [comment]
I can help. Just need to see what features of pathfinder are still in 5e for races. 

Well try and look tonight.

**Comment by grandchefpanda** [comment]
Ok I will create in less than 2 hours the Faery Dragon without scripts, so you have a clean base.

**Comment by grandchefpanda** [comment]
Faery dragon is created with id r5CMMFeaDr.

**Comment by shadowchemosh** [comment]
So of course some of this is really easy.  Then parts of it would be impossible to use if you didn't already understand races from Pathfinder. But with the Pathfinder experience this is over all pretty easy.

On the race for r5CMMFeaDr find it in the editor and click the blue button called "Fields" in the top right side.  Then add a new field called "rGiveSpec" and set the value to "1".  I assume each dragon can only have one color.  For other races you could allow 1 to many abilities to be selected if you wish.

Then copy and paste this XML into a .user file.  This is a new **Race->Racial Custom Ability** that is linked to the Faerie Dragon race.  This allows "one" of these custom abilities to be chosen by the race on the "Background" tab after selecting Faerie Dragon.

```
  <thing id="rc5CFaDraR" name="Red" description="This is an example ability that is linked to the Faerie Dragon race.  You can setup this ability just like a normal Racial Special.  But it can be selected." compset="RaceCustom">
    <tag group="AllowRCust" tag="r5CMMFeaDr"/>
    <eval phase="First" priority="600"><![CDATA[
      ~ Set our focus to the hero's race &
      perform hero.findchild[BaseRace].setfocus
      doneif (state.isfocus = 0)

      ~ Set our race's name to include the color of this ability
      focus.field[livename].text = focus.field[name].text & " (" & field[name].text & ")"]]></eval>
    </thing>
```
I added script logic that takes the name of the ability and combines it with the race so that the Color would get displayed.

I don't know what else these abilities do besides adding spells.  But you mentioned changing the CR value.

You can do that by adding the following logic after the doneif()
`focus.field[rCR].value += 1`

Focus is the "pointer" that points to the BaseRace.  Sense each hero can have only one race we don't need anything more fancy than that to get to the race.

**Comment by grandchefpanda** [comment]
Thanks, I have successfully understood this and implemented it ^^

**Comment by shadowchemosh** [comment]
Nice!
