### ISSUE TITLE
Monster Manual: Variant Monsters

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#260]
**Completed:**
Dracolich Template - Added 20 Adult and Ancient dracoliches to *stock

**Pending:**
Shadow dragon Template

Variant monsters from MM : 
Bone Devil Polearm
Erinyes rope of entanglement
Ice devil Spear
Drider spellcasting
Drow magic armor and weapon
Drow elite warrior magic armor and weapon
Drow pristess of lolth magic armor and weapon
Kuo-toa Monitor
Mind Flayer Arcanist
Psychic gray ooze
Poltergeist
Thri-kreen Weapons
Thri-kreen Psionics
Troll Loathsome limbs
Vampire warriors
Vampire spellcasters

After Creatures added by LW:
Giant lizard Hold Breath
Giant lizard Climb
Diseased giant rats
Cave bear
Swarm of beetles
swarm of centipedes
swarm of spiders
swarm of wasps

**Comment by grandchefpanda** [comment]
Dracoliches #304

**Comment by Sklore** [comment]
@grandchefpanda - What does it mean for this issue now that official variant monsters functionality is provided?

**Comment by grandchefpanda** [comment]
You mean template ?

**Comment by grandchefpanda** [comment]
Some monsters are new race, others should simply be added to stock file because for exemple they have an alternate weapon (but the race should be changed to add proficiency for this weapon)

**Comment by dungeonguru** [comment]
Did some work on this ticket and merged what I could. I used the Racial Variant Trait instead of templates for a lot of these because it is a lot less cluttered for the user that way and timing isn't as much of an issue for 90% of bootstraps. If a variant or template adds raDarkvision you need to put the following into a First/100 timed script: `perform assign[Hero.HasDarkvision]` in order for it to show up on output.

**Completed**
Created new files to hold the extra work and get out of the PHB file for clarity: COM_5ePack_MM - Templates.user, COM_5ePack_MM_Stock_File_Variants.stock
**_Idea_**: We should probably rename the PHB for monsters to MM at some point. 
Demons: Summon Demon Racial Variants
Devils: Summon Devil Racial Variants
Bone Devil: Racial Variant adds hooked polearm
Erinyes: Variant to use rope of entanglement
Ice Devil: Variant to add Ice Spear
Dracolich: Created new Dracolich template - depreciated the PHB version, will update the .stock as I get time
Dragons: Innate Spellcaster Racial Variant added 
Shadow Dragon: Created a Shadow Dragon template 
       - Bug: cannot remove bootstrapped original breath weapon with scripting, it just greys out. 
Drider Spellcaster: NPC Race created, could probably make this into a variant, but easier to call out seperate.
Elf, Drow Magic Items: These magic items can be created within the .stock file, are we wanting to create new copies of +1 to +3 armor and weapons that have a statement somewhere that these items become nonmagic after 1 hour of sunlight?
Ettercap: Web Garrote variant
Genies: Added Variants for Disguise Self, True Polymorph and Wish

**Comment by Sklore** [comment]
@dungeonguru - when you merge a branch and close out the ticket can you leave the merge code in the notes. Just type it like this #696. That then links the two together which makes it easier to track changes at a later time.

**Comment by dungeonguru** [comment]
Closing the ticket with merge #698, any new issues will be bug fixes.
