### ISSUE TITLE
Is there a better way to manage new content

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#294]
Hi Team, 

Just looking for some feedback. 

I'm not a huge fan of the current state of the release files. By this i mean we have content being released to the end-users with non-existent scripting etc which is leading to complaints. 

Is there a better way for us to operate in which we can have a DEV branch and the MAIN branch remains used for content that is 100% ready for release?

Any more experienced GitHub users floating around that can offer their experience?

Example: 
New Content > Branch (DEVELOPMENT) > Scripting / Content Complete > Branch (Main) > Public Release

Obviously we can't reverse a release. Once the file is given to the public we need to work at resolving the outstanding issues asap but can we make a change to improve things moving forward?

Let me know your thoughts.

**Comment by LordMorin** [comment]
The one time I tried to help with something, I messed things up. So all I've been doing it try up upload my work as a zip file and the professionals fit it in . . .

As for updates, my suggestion for what is is worth is to focus one one book or section at a time. When it is considered complete and bug free, then put out an update. For example, if it is something we put in 1.3 without scripts or text, once compelte you could call it version 1.31 etc.

**Comment by grandchefpanda** [comment]
This can lead to a maintenance nightmare, so we must be carefull with this.

Managing xml tags themselves could be difficult.  Perhaps make a file with the word dev in the name and put the main incomplete things in it, then when complete we move it to the main file. and if a release is made we don't include the dev files.

Exemple: 
COM_5ePack_PHB - Monsters.user
COM_5ePack_PHB - Monsters dev.user

custom abilities, even incomplete one, are all put in COM_5ePack_PHB - Monsters.user because they are not used by themselves.
the monster race that is incomplete is put in COM_5ePack_PHB - Monsters devp.user because this is the main visible thing.

So we can see everything during dev. when the monster race is complete we move the race tag from COM_5ePack_PHB - Monsters dev.user to COM_5ePack_PHB - Monsters.user

if a release id done we don't include COM_5ePack_PHB - Monsters dev.user
It should work if we only don't include unfinished main things.

I do this with the NPC like thug, commoner, guard etc, that I need for my games but waiting for LW to include ^^

**Comment by xdy** [comment]
Another option would be to add a couple of new top nodes to the 'source
selection' dialog (i.e. edit the 1st files) so that we other than the ones
we currently have (e.g. Wizards, Enworld, etc) also have Alpha and Beta.
Under Alpha we would then have the ones that we consider to be alpha
quality (incomplete, barely usable). For instance, En5ider 34 would be in
alpha.
Under Beta we would have the, well, beta, ones (text complete, mostly
scripted, user workarounds exist for missing scripts). For instance, RGG:s
Shadow warrior would then be in beta.

The definitions (and names, and number) of the categories could of course
be different, the above just sound reasonable to me.
Basically, I prefer to release early, release often/deliver a minimal
viable product and iterate (aka let the users find the bugs :), especially
as we are in a resource-constrained environment. I.e. we're a bunch of
volunteers working on the stuff that interests us.

Then we just communicate to the users whatever definitions we come up with
for the categories, and move stuff to the appropriate 'root' section when
we feel it's up to par. This way we still get some people testing early,
but at least they will know they are testing...
Also, I'm sure some are happy with just the basics. 'Placeholder' or having
to do stuff manually is kind of irritating, but at least for me, it still
beats doing a character outside of Hero Lab. Also, seeing stuff I could
easily do is what prompted me to start helping out. (Or, in some cases -
again, sorry - accidentally overwriting what others had done... Hmm. Maybe
getting more help is a mixed blessing. :)

/Jonas

**Comment by Sklore** [comment]
I quite like that idea Jonas. 

It's simple to implement,  easy to manage. Won't cause any conflicts for the user's when we move something into a completed state. And it's very clear to the end users that they are enabling something that may not be complete.

**Comment by grandchefpanda** [comment]
Like the source idea too, but I think it is best to have a beta for each source then, because without it all we be mixed in one source then good luck to find our stuff.
Have Out of the Abyss and Out of the Abyss Beta, etc

**Comment by Sklore** [comment]
That way we could release the segments of a book also. Ie spells are always ready before class options.

**Comment by xdy** [comment]
Something like this totally made up example then?
Awesome company
  'Awesome Gameworld Sourcebook'
Beta Awesome company
  'Another Awesome Sourcebook' everything but classes
Alpha Awesome Company
  'Another Awesome Sourcebook' classes
  'Yet Another Sourcebook'

I.e., AGS is wholly complete, text, scripts, everything, AAW has most
things mostly done, except that the classes are not completed, and YAS is
barely started.

Or should it be
AC
  AGW
  Beta
    AWS
  Alpha
    AWS
    YAS

(And yes, I like abbreviations. :)

/Jonas

**Comment by Sklore** [comment]
Is 3 separate branches too much (Release, Beta, Alpha)? I like the concept however I worry that the small selection panel is going to have one hell of a scroll on it to see all the options.

**Comment by xdy** [comment]
Yeah, that is a good point.
Just released (i.e. not marked) and Beta would probably be fine. (With beta
maybe meaning something like 'Most things work. Read the release notes for
details. Please tell us of any problems you find that are not noted
there.') Finer graduations is probably more effort than it's worth.

/Jonas

**Comment by grandchefpanda** [comment]
I would do for exemple
Sourcebook
-Elemental evil
--Prince of apocalypse
--Prince of apocalypse beta
--Adventure league
-Rage of demons
--Out of the abyss
--Adventure league
--Adventure league beta

and so only create temporary beta source where there a re needed

**Comment by Sklore** [comment]
Are we over thinking this perhaps? What is we just change the name of the 'source' entry to include "In-Development". 

![2016-04-06 20_54_46-photos](https://cloud.githubusercontent.com/assets/8046697/14314989/d60fb326-fc39-11e5-8e6b-878ff943f2ff.png)

**Comment by grandchefpanda** [comment]
lol

**Comment by grandchefpanda** [comment]
If we do that we need then to do sourcebooks one by one and complete it 100% or everything will be in dev.

**Comment by Sklore** [comment]
Alternatively though you need to set a unique source identifier of the 'thing' to enable you to identify it under a different heading anyway though don't you?

**Comment by xdy** [comment]
I like that idea. As long as noone creates a book named 'In development',
we're golden. :)

And as for everything being in development? Well, who cares, really?
Still better to release early, warts and all, so it can be used, rather
than endlessly polishing something.
Agile development has its flaws, but is better than being stuck in a
waterfall. :)
On 6 Apr 2016 1:25 p.m., "Sklore" <notifications@github.com> wrote:

Are we over thinking this perhaps? What is we just change the name of the
'source' entry to include "In-Development".

[image: 2016-04-06 20_54_46-photos]
<https://cloud.githubusercontent.com/assets/8046697/14314989/d60fb326-fc39-11e5-8e6b-878ff943f2ff.png>

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/Sklore/HL_DD_5e_Colab/issues/294#issuecomment-206320686>

**Comment by Sklore** [comment]
I could then update the advertisement forum with a definition of key status's. 

Example:
No status - file is released and considered 100% complete. Please report any and all encountered issues. 
Gamme - This file contains all things and is considered fully functional. You will still encounter Placeholders. Please report any errors with the mechanics of this file. 
Alpha - This file is still under heavy development. You will encounter missing thing, features and errors. 
Beta - This file is functional however some of the scripting is yet to be released

**Comment by grandchefpanda** [comment]
I would put the status at the end IMO

**Comment by Sklore** [comment]
That works

![2016-04-06 21_26_56-photos](https://cloud.githubusercontent.com/assets/8046697/14315742/577c37be-fc3e-11e5-9006-898abd672af5.png)

**Comment by Sklore** [comment]
So if your happy for this to be implemented leave your reaction to this post. Alternatively keep the discussion going below.

**Comment by Sklore** [comment]
This is now implemented. When adding new content please use the following Source flags. 

**No status** - file is released and considered 100% complete. Please report any and all encountered issues. Placeholders may be used where paraphrased text is not available. 
**Beta** - This file is functional enabling you to create a character however some of the scripting is yet to be released which may cause calculation errors.
**Alpha** - This file is still under heavy development. You will encounter missing thing, features and errors.
