### ISSUE TITLE
COM_5ePack_SCAG - Classes.user

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#331]
I was playing with building a Storm Sorcery Sorcerer and for some reason it seems to be giving me fly 60' at first level instead of at 18th level like it supposed to. I couldn't find anything saying this has been fixed.

I looked at the ability that grants it in the 1.3 version of the files I have, but couldn't see anythign wrong.

**Comment by Sklore** [comment]
Thanks @LordMorin 

I can replicate this but i cannot see why. 

xFly is associated with Wind Soul which does not trigger until L18. The special ability Wind Soul does not become visible on the Special tab until L18 yet Fly is there from L1. 

It's definitely triggering from  cCSrcWiSo. I added it to the rogue and replicated the issue there. 

I can also replicate the issue with xSwim

@shadowchemosh is this being bootstrapped properly to your knowledge?

**Comment by LordMorin** [comment]
Nice to know I am not going insane (at least any quicker than usual). :)

**Comment by shadowchemosh** [comment]
When you bootstrap something to another Thing that bootstrap comes along and becomes live and active on the hero as soon as the main Thing becomes a pick.  So when you added the class special ability called "Wind Soul" the xFly came along also and got set to 60.  You should not actually use bootstrap logic to set specials like xFly on Classes.  This technique should only be used on races where everything is gained as soon as you add a specific race.

The first way to solve this issue, which I don't recommend, is using bootstrap condition logic.  You can add a condition that says don't let the bootstrap become a Pick until so many Classes.Sorcerer tags are counted on the hero.  See this article for more on bootstrap conditions:
http://forums.wolflair.com/showthread.php?t=47611

The above locks the class ability to only work on a single class (ie Sorcerer).  At least in Pathfinder so many class abilities get shared that its bad design to lock to a single class.  In these cases I recommend using a script to simply set the abValue of the xFly ability.  xFly, xSwim etc are ALWAYS live on the hero and don't even need to be bootstrapped.

Here is the script logic I added:

```
      ~ If we're not shown, just get out now
      doneif (tagis[Helper.ShowSpec] <> 1)
      ~ if we've been disabled, get out now
      doneif (tagis[Helper.Disable] <> 0)

      field[abValue3].value += 3 + #attrmod[aCHA]
      field[livename].text = field[thingname].text & " (" & field[abValue3].value & " Creatures)"

      ~ The following should only happen once on the first copy
      doneif (tagis[Helper.FirstCopy] = 0)

      ~ If ability activated then we have only a 30ft fly
      if (field[abilActive].value = 1) then
        #value[xFly] += field[abValue2].value

      ~ Default is 60ft
      else
        #value[xFly] += field[abValue].value
      endif
```

This is a little bigger as it now 100% has the ability scripted.  It correctly only gives the fly ability at the level that we are bootstrapped at.  It also gives some nice information for the "number" of additional creatures that can be affected.  Last part is I added the 1/hour activation ability so that when you do include other creatures your flight speed changes to 30ft instead of 60ft.

**Comment by Sklore** [comment]
How are you not working for LW...

Thanks Shadow :+1:

**Comment by LordMorin** [comment]
Note for future scripting uses. It may also fix issues I had that I solved
with Bootstrap Logic.

Thx Shadow.

**Comment by Sklore** [comment]
This issue has been resolved.
