### ISSUE TITLE
UA - The Undying Light

### ISSUE THREAD

**Issue by kahnhalen** [Sklore/HL_DD_5e_Colab#420]
Requesting adding The Undying Light from the Unearthed Arcana.  Not sure if this is the right way to do it.  Thanks

**Comment by Sklore** [comment]
Source: https://media.wizards.com/2015/downloads/dnd/02_UA_Underdark_Characters.pdf

**Comment by Sklore** [comment]
Coding: How to add temporary hit points to Radiant Resilience. 
@shadowchemosh - does PF HL have the ability to track Temporary Hit Points? I can't see anything within the application that allows people to add this. 

**Temporary Hit Points**
Some spells and special abilities confer temporary hit points to a creature. Temporary hit points aren’t actual hit points; they are a buffer against damage, a pool o f hit points that protect you from injury.

When you have temporary hit points and take damage, the temporary hit points are lost first, and any leftover damage carries over to your normal hit points. For example, if you have 5 temporary hit points and take 7 damage, you lose the temporary hit points and then take 2 damage.

Because temporary hit points are separate from your actual hit points, they can exceed your hit point
maximum. A character can, therefore, be at full hit points and receive temporary hit points. 

Healing can’t restore temporary hit points, and they can’t be added together. If you have temporary hit points and receive more of them, you decide whether to keep the ones you have or to gain the new ones. For example, if a spell grants you 12 temporary hit points when you already have 10, you can have 12 or 10, not 22. 

If you have 0 hit points, receiving temporary hit points doesn’t restore you to consciousness or stabilize you. They can still absorb damage directed at you while you’re in that state, but only true healing can save you. 

Unless a feature that grants you temporary hit points  has a duration, they last until they’re deplete or you finish a long rest.

**Comment by Sklore** [comment]
@kahnhalen 

Hey mate, this has been added. It's usable but per the notes above does not track everything automatically.

**Comment by Sklore** [comment]
Download early using this link for testing: https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip

**Comment by shadowchemosh** [comment]
Pathfinder does have full support for dealing with Temp HP.  I have no clue why the logic was removed when they did 5e. =(

Only way to do this is to see if the "old" way I did in Pathfinder works in 5e.  Basically you use an adjustment/counter to artificially "increase" HP and then lower the counter when you take HP damage.  Its not perfect but it works.

**Comment by Sklore** [comment]
Thanks mate. I'll log a question to LW and see if it prompts them to add the functionality.

**Comment by LordMorin** [comment]
I couldn't find it so I created an adjustment of my own to allow me to
track temporary hp. My Adjustment bootstraps an ability of the same name.

Ability Eval Script:
Phase: Attributes, Priority: 10000

    doneif (field[abilActive].value = 0)

    herofield[tCurrentHP].value += field[actUser].value



On the Ability check the following:
- Show in Activated Abilities List?
- Choose Amount of Activation?

Incrementer label: Temporary Hit Points
Minimum: 0
Maximum: 1000

Once you create the ability, bootstrap it to the adjustment. I disabled
Incrementer on the actual Adjustment and enabled Show Info Button. I put it
in the Miscellaneous category.

This may not be the best way to handle Temporary hp, but it works for me.

**Comment by Sklore** [comment]
I have submitted a question to LW. Will await their response before implementing something ourselves.

**Comment by TheEnthusiast** [comment]
did LWD answer? I'm curious myself.

**Comment by Sklore** [comment]
Nothing yet, it's been taking them a few weeks to get back though on basic questions.

**Comment by HippyCraig** [comment]
FYI the latest release of 5e HL is Temporary Temp HP

**Comment by TheEnthusiast** [comment]
Merge #596 adds the missing THP pool.
