### ISSUE TITLE
Background - Tool Proficiencies not working

### ISSUE THREAD

**Issue by azuravian** [Sklore/HL_DD_5e_Colab#45]
When I select a background that grants a specific tool proficiency, the profiency doesn't show up under the "Skills" tab.  The only proficiencies that do show up are the ones where you select from a list, like a musical instrument or gaming set.

**Comment by shadowchemosh** [comment]
Thanks for the bug report.

For now it appears this is correct based on how Lone Wolf built things.  Only a "tag" gets assigned to the Hero. I have found a few official bugs with the way Backgrounds work and I have reported them to LW.

@Sklore I could bootstrap the Tool Proficiency to the Background thus causing them to appear on the Skills tab.  That would be a temp fix until we get some answers back from LW to how this is suppose to work because right now its not....

**Comment by Sklore** [comment]
Fixed under #48
