### ISSUE TITLE
Homebrew Pally Pack

### ISSUE THREAD

**Issue by Mozmonar** [Sklore/HL_DD_5e_Colab#453]
Not sure if this is the proper procedure for posting this...

Additional Paladin Oaths from various sources...they seem to work for the most part. Some of them could use some scripting that is beyond me.

Sources
Oaths...
Oath of Courage - En5ider 039
Oath of Despair - Boltnine Homebrew
Oath of the Purge - En5ider 025
Oath of Sunlight - Middle Finger of Vecna - http://www.middlefingerofvecna.com/2...-sunlight.html
Oath of Supremacy - En5ider 025
Oath of the Unyielding - Boltnine Homebrew
Spell...
Disintegrating Strike - https://the-dungeon-and-the-dragons....egrating-smite (one of the Oaths has this listed as a Bonus Spell which is why it is included)
[Homebrew_Pally_Pack.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/499703/Homebrew_Pally_Pack.zip)

**Comment by Sklore** [comment]
Welcome :)

There are two ways, you can either do exactly this and one of the community team can do the extra work to implement it with the pack

or... 

Join the team and learn how to add the content directly to GitHub yourself. It's really easy but it means you need to learn out naming conventions (which you are already using according to these files) and how to setup the *.1st files which control the menu options the player see's within Hero Labs (really easy). 

Let me know if you want to take the next step, happy to help run you through some stuff. From what I'm seeing in this file you already have the skills 👍

**Comment by Mozmonar** [comment]
I may just take you up on that. Still not able to do much beyond just tinkering with what has already been created. Anything more complex than that and I am totally lost. Case in point I spent about 2 hours trying to get the Oath of Sunlight Aura to apply Fire and Cold resistance but finally got it. And another 2 hours trying to get the "Incandescent Fury" ability to change the damage die for the smite from d8 to d10 with no success...I was able to make it add an additional string of text to the line but not replace what was already there. The scripting is very counter intuitive to me.

**Comment by Sklore** [comment]
I'm totally the same. I couldn't write a unique script for the life of me. That's why im working on the Wiki, as i see a snippet of code that works i copy it in with a description so I can come back and use it later. 

https://github.com/Sklore/HL_DD_5e_Colab/wiki

Also, up above use the search box. It's magnificent. If you want to do X with thing Y, just type the name of Y into search  and all the pre-existing code in the community pack will return in the result. Just paste what already works.

**Comment by Mozmonar** [comment]
I found a problem with one of these paladins. The Oath of Sunlight has an ability gained at 8th level called Sun's Warmth that adds cold and fire resistance. My implementation correctly adds the ability at 8th level but adds the resistances at 1st level. I don't know how to fix this.

**Comment by LordMorin** [comment]
Hmmm . . . I don't have that Oath. Is it in the official 5e Community Pack yet, or only available through the GIT site at the moment?

**Comment by Mozmonar** [comment]
Don't think it is in the community pack yet

**Comment by LordMorin** [comment]
Ah, I'll have to grab it if I want to look at the issues. Do you have a link to the download?

**Comment by Mozmonar** [comment]
Other than the zip file above I don't. I'm nit actually part of the community pack team. I just occasional throw some of my fumbling attempts up here.

**Comment by LordMorin** [comment]
The way you added your resistance was through an Eval Script. You didn't include a level restriction in the script. I added that and 2 other doneif's that ShadowChemosh recommends putting in to most ability scripts. They allow the ability to be disabled if needed.

Also, if you look at the source for Sun's Warth, you'll see I've added the source Various Homebrew Options. You should add this to all your sources in this file if you plan to have GIT add it to the 5e Community Pack. Otherwise users can't turn off you stuff if they don't want to use  it.

The only file I modified atm is Sun's Warmth. You may have to turn Various Homebrew Option on or remove the source from Sun's Warth if you get errors.

[Homebrew_Pally_Pack - Modified.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/609718/Homebrew_Pally_Pack.-.Modified.zip)

**Comment by Mozmonar** [comment]
Appreciate it. As I have stated many times I don't really know what I am
doing. I tinkering around in the other files and find something that does
something and then add it to something I am making without really
understanding how or why it works.

On Nov 23, 2016 1:45 PM, "LordMorin" <notifications@github.com> wrote:

The way you added your resistance was through an Eval Script. You didn't
include a level restriction in the script. I added that and 2 other
doneif's that ShadowChemosh recommends putting in to most ability scripts.
They allow the ability to be disabled if needed.

Also, if you look at the source for Sun's Warth, you'll see I've added the
source Various Homebrew Options. You should add this to all your sources in
this file if you plan to have GIT add it to the 5e Community Pack.
Otherwise users can't turn off you stuff if they don't want to use it.

The only file I modified atm is Sun's Warmth. You may have to turn Various
Homebrew Option on or remove the source from Sun's Warth if you get errors.

Homebrew_Pally_Pack - Modified.zip
<https://github.com/Sklore/HL_DD_5e_Colab/files/609718/Homebrew_Pally_Pack.-.Modified.zip>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Sklore/HL_DD_5e_Colab/issues/453#issuecomment-262599363>,
or mute the thread

**Comment by LordMorin** [comment]
That's how I started myself. Most of what I have learned came from working with existing .user files, yhe Editor's Help files, and mostly from the incredibly helpful members of these forums.

**Comment by dungeonguru** [comment]
Is anyone working on these homebrews/enhancements currently? Looking to clean up old tickets if we can.
