### ISSUE TITLE
Dueling is not being applied to thrown weapon damage

### ISSUE THREAD

**Issue by akaddk** [Sklore/HL_DD_5e_Colab#457]
Sage Advice has ruled that the fighting style Dueling applies to one-handed weapons that are thrown when no other weapon is in the other hand. I cannot figure out how to make it apply the damage bonus to throw damage.

**Comment by TheEnthusiast** [comment]
I'm not sure if you are asking as a user or as a developer. You currently cant do it as a developer, because the style is provided by the core SRD package. You need to ask Lone Wolf to fix it.

As a user:
1) Open your character in HL
2) Go to personal tab
3) Click on permanet adjustment
4) Select Damage bonus, ranged(specific weapon)
5) Select the weapon you need the bonus on and inform the +2 modifier.

That will do it.

**Comment by Sklore** [comment]
Closing as this is not related to the 5e Community Pack.
