### ISSUE TITLE
Some naming conventions problem in Backgrounds

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#46]
Background custom abilities: bBMilitiaA
Ideals: btSdIndepe
Personality traits: btBDefuse

**Comment by shadowchemosh** [comment]
Yep a few Unique ID's got missed and do not contain the 5C two digit identifier.  The issue becomes changing the Unique ID now will break anyone that used these backgrounds in characters already.  HL will toss some crypt messages if we change the unique id's to be valid.

This has not been out very long yet so you would not 'break' many characters but still possible to get some "angry" posts about it if its changed. =(

I am just laying out "information" its really up to these guys which way they want to go....

**Comment by grandchefpanda** [comment]
I prefer this is still corrected, better now than tomorrow

**Comment by Sklore** [comment]
Oh thanks for calling this out. Given how early days it is I think we certainly need to fix this.Will check it out today.

**Comment by grandchefpanda** [comment]
In class : Custom abilities, cClrTempes
I've seen also that there some domain are there twice, the one from the SDR and the one from the community file, don't know if this is normal

**Comment by Sklore** [comment]
bBMilitiaA updated to b5CMilitia
btSdIndepe updated to bt5CSdInde
btBDefuse updated to bt5CDefus
cClrTempes updated to c5CClrTemp

Testing and working OK. 

Merged as part of #ffe6af3

**Comment by Sklore** [comment]
Changes submitted: scheduled to be deployed in next release.

**Comment by grandchefpanda** [comment]
commit #24f0f9b reversed the change on the background id names

**Comment by Sklore** [comment]
Fixed under #24f0f9b 

Sorry... im going back to bed /yawn

**Comment by shadowchemosh** [comment]
Have a good night!

**Comment by Sklore** [comment]
;) I'm at work, its about 10am here unfortunately.

**Comment by shadowchemosh** [comment]
Oh man!  I keep forgetting the big time difference.  Its still Sunday night at 6pm here. I am about to have dinner and get ready for some "Walking Dead"! =)  Work is still many hours away!

**Comment by Sklore** [comment]
Going to move these to Obsolete instead.

**Comment by Sklore** [comment]
Scratch that, Obsolete tag does not seem to work with backgrounds.

**Comment by shadowchemosh** [comment]
If you are fixing "Uniqe ID's" like in this case.  You don't want to use Obsolete tags.  You need to really remove from the whole Thing from the .user file.  Because the possibility of getting a Duplicate Thing Error still exists because the Unique ID even when Obsolete will still "load" into memory.

In addition I know Mathias most likely told you to use Obsolete tag.  But honestly I never do as it does not work 100%.  The best method I have found is to create a "Deprecate" file and I use the *HIDDEN feature of the editor to hide something.  This way when its on a persons character and they load the character HL gives a "nice" warning that the Thing is not valid. =)

Here is example file for Deprecated Things from the Basic Pack.
https://github.com/shadowchemosh/HL-Pack-Basic/blob/master/COM_BasicPack%20-%20Deprecated%20Things.user

**Comment by Sklore** [comment]
Yeah it was Colen who suggested using it. Happy to use the *HIDDEN feature as your right it would be better to force the users to update versus let them keep using a broken 'thing'.
