### ISSUE TITLE
Silvered Weapons and weapon skill feats.

### ISSUE THREAD

**Issue by CptCOOTS** [Sklore/HL_DD_5e_Colab#509]
I just noticed that the feat fell handed does not add +1 to the attack bonus for silvered versions of the weapons.

**Comment by TheEnthusiast** [comment]
It happens to all weapons using gizmos. Somehow, they seem evade the loop on the hero's weapons.

**Comment by Sklore** [comment]
So if this issue is coming from the use of Gizmo's is it something we can fix or a core pack issue?

**Comment by TheEnthusiast** [comment]
@CptCOOTS @Sklore 

Seems a bug to me. The foreach loop used to add the bonus to the weapons is the same used by Great Weapon Master or Sharpshooter feats. And both work with either magical or silvered weapons.
I'm suspicious tough. Fellhanded works at "First" and the others work at "pre-levels". Also, GWM and SS subtract "atmBonus"/"atrBonus" and Fellhanded uses "wAttMelee".

I've tried using the same attributes, and/or change the timing, but it does not seem to work. Has anyone else tried checking these items?

**Comment by TheEnthusiast** [comment]
@Sklore 
So, in the end, it WAS a timing issue. Moving the script from First/100 to Post Levels/10000 made the trick for Fell-handed, Flail Mastery and Blade Mastery. Spear mastery needed a new script because it only worked if set against charge was marked. 

Also, I found out that Scimitar do not receive the wGroup.Sword for some reason. I decided to open a bug report with LWD in order to get that fixed.
