### ISSUE TITLE
New Request: Monk: Way of the Four Elements

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#525]
**Monk: Way of the Four Elements**
Thread: http://forums.wolflair.com/showthread.php?t=56941
User File: https://drive.google.com/open?id=0BwZoXORhZHGwT1RLOURNNnpXREk

**Comment by dungeonguru** [comment]
I can try to get this into the next release in the COM_5ePack_Homebrew - Classes file, but what category - should it get its own subcategory under Homebrew options or get lumped into the "Various Homebrew Options?"

The file has way more than the monk - I'll trim out what isn't directly part of the revamped Way of the Four Elements though.

**Comment by dungeonguru** [comment]
OK, removed all the non-Way of the Four Elements stuff from the file and moved the * from the front of the abilities to the end so that they are listed after the original ability rather than all up front when this option is chosen. I also have changed the monastic tradition name to read "Way of the Four Elements: Remastered" rather than the Wot4E provided. 

My preference would be to create a new selectable under the homebrew options rather than lump it in the middle but I'll wait for any input before pulling the current files and appending the information I just adjusted.

**Comment by Sklore** [comment]
Adding a new selectable is quite easy. You need to give this a new source and then define that source in the Home Brew *.1st file. Just have a look at the file and you should pick up how it works. Would just need to copy a chunk of code and make changes to the source and description sections.

**Comment by dungeonguru** [comment]
Commited the two updated files:
  COM_Source_110 - Third Party Publisher.1st
  COM_5ePack_Homebrew - Classes.user
