### ISSUE TITLE
Downtime Journal

### ISSUE THREAD

**Issue by Gmanor** [Sklore/HL_DD_5e_Colab#539]
Would it be possible to create a way to add downtime addition to the journal sort of like gold? That way it's tracked and is treated as an expendable resource?

**Comment by LordMorin** [comment]
Are you asking for modifications to be made to the existing Downtime
Journal? If so, that you would ahve to put in a suggestion to Hero Labs for
since it is hard coded.

If you are asking for a downtime journal to be added, it is already in the
system, but you may have to enable it under Configure Hero. . .

**Comment by Sklore** [comment]
Yes this functionality is already implemented. 

You need to enable it under Configure Hero.
