### ISSUE TITLE
Human Variant Subclass MUST be selected?

### ISSUE THREAD

**Issue by MNBlockhead** [Sklore/HL_DD_5e_Colab#57]
Thanks once again to everyone who put in the time to get the DD5e Community Pack out. It is VERY MUCH appreciated. 

I did have one question, however. If I choose "human" then I *must* choose a sub-race. The only sub-race is "variant human." There does not seem to be any way to NOT select a sub-race nor select a "custom" sub-race. I do indeed have to create some characters that used the variant human option, so I am glad that this option is available, but what should I do for humans that do not use the variant human rule?

Is it expected that I just ignore the validation error or is it expected that I would create some sub-races?

**Comment by Sklore** [comment]
http://forums.wolflair.com/showthread.php?t=55115

Turns out I have two different solutions installed for Human Variant. One is provided by the Community Pack. The other is an alpha release. 

Until this is released officially I should be able to copy the solution I have been provided into the Community Pack.

**Comment by Sklore** [comment]
Need someone to test my current branch. 

I have made it so there is only one Human Variant and it is now optional. Concerned the files I have been provided may be linking things that are unique to that file so want to test before this is pushed to the main code.

**Comment by Sklore** [comment]
Closing as Variant Human is now provided by the official pack. 

Have moved our version to Obsolete.
