### ISSUE TITLE
Ranger 2016 missing fighting styles

### ISSUE THREAD

**Issue by TheEnthusiast** [Sklore/HL_DD_5e_Colab#588]
http://forums.wolflair.com/showpost.php?p=243096&postcount=369

**Comment by Sklore** [comment]
This is by design. It's not a valid option:

At 2nd level, you adopt a particular style of fighting as your specialty. Choose one of the following options. You can’t take a Fighting Style option more than once, even if you later get to choose again.
Archery - You gain a +2 bonus to attack rolls you make with ranged weapons.
Defense - While you are wearing armor, you gain a +1 bonus to AC.
Dueling - When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.
Two-Weapon Fighting - When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack.
