### ISSUE TITLE
Elemental Adept doesn't allow Fire as a choice

### ISSUE THREAD

**Issue by hardvice** [Sklore/HL_DD_5e_Colab#59]
n/t

**Comment by Sklore** [comment]
Fix will be pushed in the next release.

**Comment by shadowchemosh** [comment]
I am confused on this one to fall back to a user entered array of values?   I added "Selection" helpers for the different energy types in the "Helper Things" file.  Looks like I missed fire.  I am going to correct that now and put the feat back to using a selection helpers.  That the allows any feat or ability to use those selections helpers and then to pull/test the Energy tags to figure out which "type" of energy is chosen.

Using selection helpers not user arrays is the better method moving forward.  It simplifies so many tasks you will have to do in scripts.

**Comment by Sklore** [comment]
I tried to do this originally but was editing the wrong file obviously.I tried updating in COM_5ePack - Tags.1st which was obviously incorrect.

**Comment by shadowchemosh** [comment]
That is half the issue. The selection helper in the helper thing file was the 2nd part. 

Oh damn I know the issue. 5e editor does not have a selection helper tab. I added one for the pathfinder community in the Basic pack. I can do the same for 5e allowing an easy way to make and maintain them. 

Right now you can only see the selection helpers in the RAW XML file. =( oops I forget because I so often work outside the editor.
