### ISSUE TITLE
theugy fault

### ISSUE THREAD

**Issue by trs31** [Sklore/HL_DD_5e_Colab#593]
theurgy arcane tradition dose not allow you to add cleric spells once all domain spells added.
[test.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/786062/test.zip)

**Comment by TheEnthusiast** [comment]
Hello,

There's two things here:

First, the full cleric spelllist is allowed from level 11th onward, since it's the earliest point where you have all your domain spells. Remember, you pick one per level, starting at level 2, and each domain has 10 spells.

Second, the script mistakenly counts you memorized spells as well. This is a bug we'll fix. For the time being, unmemorize your memorized spells before trying to add new ones to your spell book. The cleric spells will show up.

**Comment by trs31** [comment]
That makes sense I knew I had seen it working in a previous build but couldn't figure out why it wasn't any more. Thanks

On 19 Feb 2017 8:27 p.m., TheEnthusiast <notifications@github.com> wrote:

Hello,

There's two things here:

First, the full cleric spelllist is allowed from level 11th onward, since it's the earliest point where you have all your domain spells. Remember, you pick one per level, starting at level 2, and each domain has 10 spells.

Second, the script mistakenly counts you memorized spells as well. This is a bug we'll fix. For the time being, unmemorize your memorized spells before trying to add new ones to your spell book. The cleric spells will show up.
