### ISSUE TITLE
herbalism/poison/alchemy homebrew

### ISSUE THREAD

**Issue by sirdigbychknczr** [Sklore/HL_DD_5e_Colab#604]
We just added this to our weekly game, its fantastic and would be a great addition to the community files imo.

https://www.reddit.com/r/dndnext/comments/3w1log/5e_herbalism_alchemy_v12_updates_fanmade/

**Comment by Sklore** [comment]
Have you tried entering these yourself? These are just items and should be relatively easy to do. 

I'll be honest, I don't have capacity in the near future to take this on. Not sure about any of the other guy though.

**Comment by dungeonguru** [comment]
Entering the herbs is easy enough given the nice PDF. My question is if you are asking for more than that - modifying the potion items to allow modifiers from ingredients would be a major overhaul of the potion item type from LoneWolf and not the community.

Entering in custom potion names for every variant would require that someone provide those names or at least the rules on how to consistently name them - the "Potion of Delayed Potent Healing" in your example - how did you decide to add the modifier Delayed and Potent to a potion of healing given you used 3 ingredients.  Does using Genko Brush always mean Delayed is added while every potion that starts with Sageroot is called a potion of healing? 

I didn't do the math, but a 1 base effect ingredient and up to 3 modifier you have a very large group of items that would have to be input individually, since each 1 base has 7 versions (1 with nothing, 3 with 1 modifier, 2 with 2 modifier, 1 with all three).

**Comment by sirdigbychknczr** [comment]
Honestly, when I originally suggested adding this I wasn't really interested in adding the potions and herbs specifically, but rather the skill and abilities items to populate the skills list.

custom potions and herbs (as trinkets) can be easily tracked already.

**Comment by dungeonguru** [comment]
I think the 5e rules already cover the skills, you've just spelled them out differently. 

**Identifying an herb** : a 1d20 + Intelligence modifier 

-    **If** you have Nature skill proficiency or herbalism kit proficiency you can add your proficiency bonus to the check. Neither proficiency is required.

**Crafting a potion of healing:** a 1d20 + Intelligence modifier + proficiency bonus

-   you can only do this if you have proficiency with herbalism kit
-   From the description of herbalism kit: "Also, proficiency with this kit is required to create antitoxin and potions of healing (PHB 154).

**Crafting/Using a poison**: a 1d20 + Intelligence modifier + optional proficiency bonus

- You don't have to have any proficiency to try.
- From the description: "Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to craft or use poisons.

**Crafting a potion of hill giant strength**: a 1d20 + Intelligence modifier + optional proficiency bonus

- You don't have to have any proficiency to try.
- From the descriptions of artisan tools: "Proficiency with a set of atisan's tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft. "
- Alchemist's supplies is a tool proficiency.

I used Intelligence in these examples but some of these could be Dexterity or Wisdom checks easily.

I think you've added some nice mechanics to help set the DC of crafting an item and adding situational bonuses and penalties to the ability checks, but I think ultimately its an overlap with what is there already for the skills since the proficiency bonus can only be added once to any ability check (p174 of PHB: "If a circumstance suggests that your proficiency bonus applies more than once to the same roll, you still add it only once and multiply or divide it only once.")

In any case you don't have to have Nature skill or Herbalism kit to identify a given herb, but someone with those proficiencies will be better at identifying than someone who isn't.

**Comment by Sklore** [comment]
I don't know if this is actually possible to be honest. Creating the skill itself is easy enough but telling the program it needs to load this in appears to be coded in at a deeper level that I don't think we have access to. As such I'm closing this for now as it doesn't appear to be something we can do.
