### ISSUE TITLE
UA Cleric Domain "Forge" ability "Blessing of the Forge" seems to automatically assign a +1 to armor.

### ISSUE THREAD

**Issue by MindReaper1** [Sklore/HL_DD_5e_Colab#606]
The Cleric domain "Forge" from the Unearthed Arcana lets you imbue magic into a weapon or armor at 1st level once per long rest.  The effect lasts until the next long rest.  This gives the armor a +1 bonus to AC or gives the weapon a +1 bonus to attack/damage.  Right now, it seems to automatically give a +1 bonus to AC without allowing for weapon or external use.  This should instead be a trackable ability rather than always assume that the +1 should go towards armor class.

**Comment by TheEnthusiast** [comment]
It is a trackable ability. What seems to be the problem is that the script for Soul of the forge is working before level 6 as well.

Enviado de meu ASUS

-------- Mensagem Original --------
De:MindReaper1 <notifications@github.com>
Enviado em:Wed, 15 Mar 2017 16:04:06 -0300
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:Subscribed <subscribed@noreply.github.com>
Assunto:[Sklore/HL_DD_5e_Colab] UA Cleric Domain "Forge" ability "Blessing of the Forge" seems to automatically assign a +1 to armor. (#606)

**Comment by Sklore** [comment]
Soul of the Forge will now trigger correctly at level 6. 

https://github.com/Sklore/HL_DD_5e_Colab/wiki/Bootstrapping-Methods
