### ISSUE TITLE
Artificer throwing errors

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#609]
I have tested Artificer recently and it is constantly throwing me errors.
![artificer error 1](https://cloud.githubusercontent.com/assets/17392134/24361016/7930196e-12ce-11e7-83f0-d63a1121bd7d.PNG)
![artificer error 2](https://cloud.githubusercontent.com/assets/17392134/24361015/792fa9fc-12ce-11e7-9c7c-21e58cdc97ab.PNG)
![artificer error 3](https://cloud.githubusercontent.com/assets/17392134/24361018/79323618-12ce-11e7-98ab-236b80b4e67b.PNG)
![artificer error 4](https://cloud.githubusercontent.com/assets/17392134/24361017/7930640a-12ce-11e7-849e-a96910411596.PNG)
![artificer error 5](https://cloud.githubusercontent.com/assets/17392134/24361013/792f2d60-12ce-11e7-9c18-6ad6024bb9f5.PNG)
![artificer error 6](https://cloud.githubusercontent.com/assets/17392134/24361014/792f4e9e-12ce-11e7-85a1-e02303deaf03.PNG)
![artificer error 7](https://cloud.githubusercontent.com/assets/17392134/24361019/793b79bc-12ce-11e7-843e-d474309fee90.PNG)
![artificer error 8](https://cloud.githubusercontent.com/assets/17392134/24361021/7940ba62-12ce-11e7-8c12-84bab54312bd.PNG)
![artificer error 9](https://cloud.githubusercontent.com/assets/17392134/24361020/793ced7e-12ce-11e7-8e98-93a957fe160b.PNG)

**Comment by LordMorin** [comment]
I've been getting these errors off and on since the previous to last
official update came out. I thought it was stricty a conflict with some of
my own custom material. I had yet to resolve the issue, but since it wasn't
causing crashes I ignored it. It is very annoying though.

You are the first individual who has posted that they are having the exact
same issue.

Do you use any custom material of your own other than the community pack?



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DarkHayZe** [comment]
Just a couple items. Nothing scripted... If I could script I would have probably fixed a few other things by now...lol

**Comment by Sklore** [comment]
I am unable to replicate these errors which indicates there is an issue with something else. Please email LWD per the popup message for support.

**Comment by LordMorin** [comment]
One thing I discovered about this error is that it only seems to occur if you have a familiar, mount, or hireling attached to a character. Can anyone else confirm this? I personally, to date, have not got this error on a character without one of these three items attached to it but have had the error start occuring immediately after attaching one of them.

**Comment by Sklore** [comment]
Yeah I closed this because it doesn't sound like our issue. This needs to be raised with LWD so they can figure out the issue. If it's with us, they reach out to me usually.
