### ISSUE TITLE
Spell-less Ranger is not loading

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#610]
Downloading from the repository, is not giving me the option for the spell-less ranger. Manually downloading does not add it either.

**Comment by Sklore** [comment]
I suspect you downloaded JUST the spell-less ranger file. 

You need to download the whole pack. This is because the option to enable the spell-less ranger is built into other files that control the menu stuff. Get the whole thing using the link below. I have tested and confirmed that I can select the Spell-less ranger. Don't forget to enable 5e Unearthed Arcana - Modifying Classes option using the Ctrl - K menu.

https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip

**Comment by DarkHayZe** [comment]
For my own reference, and future use... Which file needs to be modified for adding new classes?

**Comment by Sklore** [comment]
You would want to create a new file not modify an existing one. Watch this video. I discuss this question. 

https://youtu.be/m4LhJJZ3f6E?list=PLV5XWfKkFpk6_sDYWWKwvP8zs_qVSrzoM

**Comment by DarkHayZe** [comment]
I don't mean to be a pain, I know you are busy with your own stuff, and the rest of the community pack... But I am having a little trouble getting this class thing sorted.

I was able to get it to populate in the Classes list, but I cannot figure out how to get it to populate a class tab. Any help would be greatly appreciated.

**Comment by Sklore** [comment]
Can you link me a copy of your user file. The class tab should just work.

**Comment by DarkHayZe** [comment]
[Background.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/902023/Background.zip)

**Comment by Sklore** [comment]
Ok you are going to have all kinds of issues with that file. Primarily because its a direct copy of the files that will be released by the community pack. 

1. Take everything related to the Spell Less Ranger out of the file. 
2. Download the entire Community Pack from GitHub
3. Put the files in your 5e folder. 
4. Restart HL

You should now see the option for the Spell Less Ranger exists.

**Comment by DarkHayZe** [comment]
Right, I have the "official" spell-less ranger, however the group I am in merged the revised ranger with the spell-less ranger (something WotC should have done by now), which is what I am trying to create here.

Unless I am missing something, taking those steps would just reset me back to the "official" spell-less ranger.

**Comment by Sklore** [comment]
Ah right, that's a whole different issue then and yes the steps above was just to get you to the official spell-less ranger.

**Comment by Sklore** [comment]
Getting a heap of errors with this. Attempting to figure out why.

**Comment by Sklore** [comment]
Ok NFI why. But try untick the Sources (5e Unearthed Arcana - Modifying Classes)

**Comment by Sklore** [comment]
Yeah replicated it again on my end. Having the source ticket triggers the error. No idea why or how...

**Comment by DarkHayZe** [comment]
I got past that issue, idk how I fixed it but I did...lol
Well thats not completely true, I started over....

Now I got Favored Enemies showing up twice in the "Specials" star popup at level 1, maneuver at level 2 & 9


[Background.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/902223/Background.zip)

**Comment by DarkHayZe** [comment]
Ignore the maneuvers, idk why I did that.

**Comment by DarkHayZe** [comment]
Yay bugs galore... Now it is only giving me 1 skill, and I have a timing report error. Of course it doesn't say what the error is, so I have no idea what to do to fix it.

And Greater Favored Enemy is showing at level 6 and 7 under the special abilities star, in addition to the duplicate Favored Enemies at level 1.

**Comment by Sklore** [comment]
My suggestion would be to find a custom class and build that in the tool first. Simply as practice. Doing it from brand new will teach you alot and then move on to merging the two classes together.

**Comment by DarkHayZe** [comment]
I made a lot of progress on this today. I have a couple small issues but overall it is done. Even with a custom Conclave for the Spell-less Ranger.
