### ISSUE TITLE
Request for Additional Content

### ISSUE THREAD

**Issue by PlatinumKobold** [Sklore/HL_DD_5e_Colab#615]
Could you please add the Oath of the Common Man and Oath of Free Commerce to the 5e community pack? I need it for an upcoming game. https://www.reddit.com/r/UnearthedArcana/comments/3hy3qi/5e_the_common_man_and_free_commerce_paladins_both/

**Comment by Sklore** [comment]
Might be able to have a look at this but only If provided with a usable copy of the pdf/content. We can't copy the text out of anything from Warlock due to the protection he puts on his pdfs and sorry but I don't have time to manually type them out. 

Fair warning: my schedule is full so I personally can provide no time-frame for completing any new requests at this stage but will try help where possible.

**Comment by PlatinumKobold** [comment]
Thanks for the quick reply, I will attempt to contact the author and see
what can be done, or just type it out myself.

**Comment by Sklore** [comment]
I have tried to contact him previously with no luck btw. If you find a successful way let me know as I would love to put some of his content into Realm Works for people.
