### ISSUE TITLE
Tool Proficiencies missing from Skills Tab

### ISSUE THREAD

**Issue by Sintei01** [Sklore/HL_DD_5e_Colab#636]
I am making a Rogue and i keep getting errors for not picking a new tool proficiency but the tool proficiency area in the skills tab is completely missing.  any idea why this is?

Error: Extra Tool Choices: Resource Underspent 0 of 1

**Comment by LordMorin** [comment]
If you are a rogue and picked a background that also grants Thieves' Tools, then you get to replace 1 set of thieves' tools with another skill.

Without know more about you build its hard to say what other issues might be causing the problem.

Rogue & Criminal, Urchin, and Spy are all Hero Lab supplied. If any of these are causign the issues then HL needs to be contacted since we can't fix them since they are not part of the Community pack.

**Comment by Gladiator66** [comment]
The Tool Choices display problem appears to apply to all of the backgrounds that have tool proficiencies that are not selected. The only tools that display in the Skills tab are those that must be selected on the background tab when generating a character. The tool proficiencies that are not selected do not display on the Skills tab or in the Skills and Feats section of the main character display. I verified that the correct tool proficiencies are selected under "Tool Proficiencies" in the individual Backgrounds in the Hero Lab editor.

**Comment by LordMorin** [comment]
This issue was fixed by HL a while back. The community pack also fixed the similar issue with tools with the stuff we added.

Are you sure both you HL and the Community Pack are up to date?

In addition, if you created any material that adds Tools yourself, they may need to be updated.

If this is a pre-existing character, you may want to recreate a test version to see if the issue repeats.

**Comment by Gladiator66** [comment]
I had thought my SRD and Community Pack were up to date. However, I did some checking and saw that it was not actually updating. I had originally created a 2nd 5e folder where I was making my modifications. The original 5e folder was updating, but when I thought I was updating the 2nd folder, it was actually updating the first folder a 2nd time. 

Also, I learned that a folder containing spaces in the name will not update. Once I corrected these problems, I was able to get the tool proficiencies working. Thanks for the help.
