### ISSUE TITLE
Procedure Modification

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#655]
Is there anyone still around who knows how the procedure for adding skills/tools works. I need to make a version that includes languages.

**Comment by dungeonguru** [comment]
You might want to PM shadowchemosh on the LW boards since he wrote the original procedures.

I've deciphered that the procedure 5CAddProf is used to call the configurable/page cfg5CProf, which in turn is bootstrapped in the 5e Community mechanic meh5C. 

The procedure is found in "COM_5ePack - Procedures.user".
The mechanic and configurable are found in "COM_5ePack - Helper Things.user". 

Inside the configurable you would need 2 new fields that have a value of "component.BaseLang & !Helper.Obsolete" to hold the language choices.  This is where I get lost, I'm not sure how to add the fields here because you get an error that the fields don't exist to be manipulated. 

And of course, the procedure you'd add the variable NumOfLang to handle the language piece.
