### ISSUE TITLE
Filth's Bane

### ISSUE THREAD

**Issue by Chawpped** [Sklore/HL_DD_5e_Colab#656]
The spell is now a ritual, and the components aren't accurate to the newer PDF. 

Might be worth reviewing the new version entirely, it may have more updates: https://drive.google.com/file/d/0B0Qx4NeOkTzTZ2lrT2JoeUxQclU/view

**Comment by dungeonguru** [comment]
I think the new home for the not really complete tome of spells is on homebrewery now: http://homebrewery.naturalcrit.com/share/S1-zodGyfb
The changelog on that document states there have been at least 2 more updates to the document since this ticket opened.

**Comment by Sklore** [comment]
They did a hug update. At this stage it would probably be more efficient to input it all again than it would be to try and identify all the changes and fix. I have a parser for entering these in quite efficiently.

**Comment by dungeonguru** [comment]
Cool, I'll leave this to you.

You willing to share the parsing code or at least let me know which script language you're partial to?

**Comment by Sklore** [comment]
It's Excel 👍 haha super technical. 

https://drive.google.com/file/d/0B_6BXlzLTlj8TWdldzZ0OTE4d0k/view?usp=sharing

You paste the spell into Excel and it spits out the HL coded version. Add it into the *.user file using a text editor and off you go. Works a treat for spells. I did the same thing for monsters at one stage but it could only do the base monster not all the extra abilities etc.

**Comment by dungeonguru** [comment]
Was looking to see if I could script out for this and noticed that the original spell requested (Filth's Bane) is now missing from the source. @Sklore have you made any progress on this one? I'm wondering if we should delay or remove support on this source until we find something that can automate the process better. It will be difficult since the source material can be changed at will and there's no easy way to tell what changed beyond a "we try" effort.

**Comment by Sklore** [comment]
Sorry I dropped out of this convo. No i didn't make any progress. My spreadsheet should still work to bring it in but the only efficient way I would know to do this is to bring it all in again. I can usually do a spell book in 1-2 nights using the spreadsheet.
