### ISSUE TITLE
wrong damage for second weapon dual wielded

### ISSUE THREAD

**Issue by mercenary-kantor** [Sklore/HL_DD_5e_Colab#684]
For someone using the Ranger 2016 and Fighter multiclass, Dual Wielding Feat with Long Swords and Gauntlets of Ogre Power:  the printout adds damage wrong for the offhand of the main weapon and the main hand of the secondary weapon.

**Comment by dungeonguru** [comment]
Can you provide a portfolio of the character?

Dual Wielding allows you to use the two longswords, but unless the fighter or ranger chooses two-weapon fighting style, the offhand weapon does not get the ability score modifier as a bonus to the damage. I tried recreating but can't see the issue you are experiencing.

**Comment by mercenary-kantor** [comment]
here is the portfolio.  When it prints, the damage is wrong for the second weapon.
On Wednesday, August 2, 2017, 11:07:11 AM EDT, dungeonguru <notifications@github.com> wrote:


Can you provide a portfolio of the character?

Dual Wielding allows you to use the two longswords, but unless the fighter or ranger chooses two-weapon fighting style, the offhand weapon does not get the ability score modifier as a bonus to the damage. I tried recreating but can't see the issue you are experiencing.

**Comment by dungeonguru** [comment]
Github rejected the attachment.  I am using the pre-release files, so some fix might have been snuck in. 

I built a 2nd level human ranger (2016 and normal) with STR 13/  DEX 13 (both +1 to damage), given two longswords and wearing Gauntlets of Ogre Power (Attuned, STR 19 bonus = +4)

Case 1: **no** two-weapon fighting style,  **no**: Dual Wielder
     Main Hand: +6 to hit, 1d8+4 damage
     Off-Hand: +6 to hit, 1d8 damage - **Validation Error** - 2nd hand does not have property light
     **Result:** As expected, 2nd hand is not a light weapon, should not be able to use it, but is highlit red

Case 2: **Yes** Two-Weapon Fighting Style, **no** Dual Wielder feat
    Main Hand: same as above
    Second Hand: same as above - **Validation Error** - 2nd hand does not have property light
    **Result:** as expected, 2nd hand is invalid configuration.

Case 3: **No** Two-Weapon Fighting style,  **has** feat Dual Weilder
  Main Hand: +6 to hit, 1d8+4 damage
  Off-Hand: +6 to hit, 1d8 damage
  Result: As expected, Dual Weilding allows the non-light longsword to be equipped without error. Damage is not increased since fighting style two-weapon fighting is not selected

Case 4: **Yes** Two-Weapon Fighting Style, **Yes** Dual Wielder feat
  Main Hand: +6 to hit, 1d8+4 damage
  Off-Hand: +6 to hit, 1d8+4 damage
  Result: As expected, Two-weapon Fighting Style increases damage, Dual Wielder allows 2nd non-light longsword. 

So, those are the four cases and each one works as expected. I re-read the rules for Two-Weapon fighting and the two-weapon style and the feat Dual Wielder and can't see why it's not working for you unless a fix is already in the next release.

Two Weapon Fighting (p195: PHB): When you take the Attack action with a light melee weapon in one hand, you can take a bonus action to attack with a light weapon in your other hand.  Both weapons must be light, Ignore the ability modifier on the off-hand.   (So: if you have longsword in one hand and a longsword in the other, you can only make 1 attack with one longsword).

Two-Weapon Fighting Style: (p91: PHB): When you engage in two-weapon fighting, you can add your ability modifier to the second attack. (longsword/longsword - You cannot make the second attack since it violates the rule of Two Weapon fighting - the 1st and 2nd weapons do not have the Light property).

Dual Wielder: (p165: PHB): One of the points states you can use two-weapon fighting even when the two one-handed weapons do not have the Light property. (longsword/longsword, can make two attacks, the 2nd one DOES NOT get the ability bonus unless the wielder has two-weapon style).

**Comment by mercenary-kantor** [comment]
On my character sheet, I have two longswords:  one marked in the first (main) hand and one marked for the second (off) hand and when I print the character out the second weapon prints 1d8+8 damage.Yours in the Kingdom, Merc-Kantor.

On Friday, August 4, 2017, 3:39:50 PM EDT, dungeonguru <notifications@github.com> wrote:


Github rejected the attachment. I am using the pre-release files, so some fix might have been snuck in.

I built a 2nd level human ranger (2016 and normal) with STR 13/ DEX 13 (both +1 to damage), given two longswords and wearing Gauntlets of Ogre Power (Attuned, STR 19 bonus = +4)

Case 1: no two-weapon fighting style, no: Dual Wielder
Main Hand: +6 to hit, 1d8+4 damage
Off-Hand: +6 to hit, 1d8 damage - Validation Error - 2nd hand does not have property light
Result: As expected, 2nd hand is not a light weapon, should not be able to use it, but is highlit red

Case 2: Yes Two-Weapon Fighting Style, no Dual Wielder feat
Main Hand: same as above
Second Hand: same as above - Validation Error - 2nd hand does not have property light
Result: as expected, 2nd hand is invalid configuration.

Case 3: No Two-Weapon Fighting style, has feat Dual Weilder
Main Hand: +6 to hit, 1d8+4 damage
Off-Hand: +6 to hit, 1d8 damage
Result: As expected, Dual Weilding allows the non-light longsword to be equipped without error. Damage is not increased since fighting style two-weapon fighting is not selected

Case 4: Yes Two-Weapon Fighting Style, Yes Dual Wielder feat
Main Hand: +6 to hit, 1d8+4 damage
Off-Hand: +6 to hit, 1d8+4 damage
Result: As expected, Two-weapon Fighting Style increases damage, Dual Wielder allows 2nd non-light longsword.

So, those are the four cases and each one works as expected. I re-read the rules for Two-Weapon fighting and the two-weapon style and the feat Dual Wielder and can't see why it's not working for you unless a fix is already in the next release.

Two Weapon Fighting (p195: PHB): When you take the Attack action with a light melee weapon in one hand, you can take a bonus action to attack with a light weapon in your other hand. Both weapons must be light, Ignore the ability modifier on the off-hand. (So: if you have longsword in one hand and a longsword in the other, you can only make 1 attack with one longsword).

Two-Weapon Fighting Style: (p91: PHB): When you engage in two-weapon fighting, you can add your ability modifier to the second attack. (longsword/longsword - You cannot make the second attack since it violates the rule of Two Weapon fighting - the 1st and 2nd weapons do not have the Light property).

Dual Wielder: (p165: PHB): One of the points states you can use two-weapon fighting even when the two one-handed weapons do not have the Light property. (longsword/longsword, can make two attacks, the 2nd one DOES NOT get the ability bonus unless the wielder has two-weapon style).

**Comment by aarcc** [comment]
I noticed when I got the PDF of my PC (Sorcerer) my off hand dagger still had the damage bonus added. Will the bug be fixed or is it an Hero Lab rather than a community pack issue?

**Comment by dungeonguru** [comment]
This appears to be a print bug that's LW related. I have opened a ticket - will have to wait for an answer. The current character sheet shows the main hand and two-handed damage (for versatile) but not off-handed. This works correctly in the output statblock option.

**Comment by Fenris447** [comment]
Closing since this is a LW issue we can’t fix.
