### ISSUE TITLE
Gothic Heroes - Revenants and Racial Feats

### ISSUE THREAD

**Issue by kjbro** [Sklore/HL_DD_5e_Colab#715]
Revenants are currently listed as their own race, rather than a subrace option.  This hasn't been an issue until now, with Racial Feats.  

Example to reproduce: Revenant (Dwarf) taking the Grudge-Bearer feat generates a validation error due to character not being a Dwarf.

Correct handling: Character should list as Dwarf (Revenant) rather than Revenant (Dwarf), as Revenant is a subrace.

Alternative fix: If leaving Revenant as race, make "original race" count for feats somehow?

**Comment by dungeonguru** [comment]
The lockdown for that feat could be modifed from #hacerace[rDwarf] to look for the type tag ttDwarf (or whatever it is).  I didn't think the release was in the public yet, so easy to fix.

**Comment by kjbro** [comment]
This would have to be fixed on every racial feat.  This technically also affects other racially locked content (Bladesinger wizard, Battlerager barbarian, etc.)

**Comment by LordMorin** [comment]
A fix might be to create an adjustment that adds the race as a type and/or a sub-type.

**Comment by kjbro** [comment]
Would that be easier than creating a subrace for revenant that's multi-attached to many races?

**Comment by LordMorin** [comment]
I am not sure which is why I suggested an adjustment for now. When I am
feeling better, I'll take a look into it but I suspect this will be the
easier method at this time.

**Comment by dungeonguru** [comment]
After looking, its more complex. The revenant uses subraces (Dwarf, Elf, etc) rather than racial tags. It's easy enough to change restriction locks to a subrace but this points out that all the VGtM player races aren't available as Revenants either, so it's worth a conversation on whether or not to rewrite Revenant as a subrace option for all the current player races (depreciating the current version) or to continue on and create a bunch of subraces for Revenant AND update all the racial content to allow the Revenant subraces access to them. 

I would vote to rewrite the Revenant as a subrace, because that's how the UA article presents it anyway - which means nothing with a race restriction needs to be touched. But there might be reasons this could be impossible.

**Comment by LordMorin** [comment]
The one major issue I can see with the Relevant as a sub-race is the one I
ran into when I was creating my own version (before switching to the
community version) and that is you'd have to add the sub=race to each and
every race. :(

**Comment by kjbro** [comment]
So, I took a look at this, and it looks like with the "Subrace Of" tag a
Revenant subrace could be created and tagged to any race with a subrace
choice.  Then a separate Revenant subrace could be copied and modified for
the unique situations called out in the UA article (dragonborn, human).
Theoretically revenant could be added to any of the later races (such as
VGTM races) but it would have to be derived based on the article's formula
for non-subrace races.

**Comment by dungeonguru** [comment]
Hm, I would rather write one subrace that fits most cases, and a few subraces for those that don't rather than a bunch of subraces for every player option that comes out in the future. Adding the revenant subrace to a new race is then just a matter of clicking the checkbox on the revenant subrace of list rather than creating a new subrace, and then tracking down all racially coded feats, magic items, subclasses, etc and modifying their code too. A lot less invasive.

**Comment by dungeonguru** [comment]
Acutally, how many of the races have a subrace?
Dwarf, Elf, Genasi, Gnome and a few others in homebrew if we wanted to extend support. The other revenants specificially mentioned are Human and Dragonborn - which means all the other races don't have rules to make revenant yet. So, you would only have to copy the initial Revenant subrace maybe 6-ish times and make the two "special cases"? Not sure if the Black Magic tiefling subraces should count since the SCAG tieflings are variants, not subraces...

**Comment by dungeonguru** [comment]
So, what I've done is depreciated the current revenant race and added:
1. A dragonborn revenant draconic ancestry : this choice will ask for your original draconic lineage and uses it to set the breath weapon shape - it otherwise ignores the old resistances and sets necrotic damage type.
2. A revenant subrace for the community aasimar (VGTM), dwarf, elf, genasi, gnome, halfling and tiefling races. I also made a revenant subrace for the UA article That Old Black Magic tiefling variant, which is getting uploaded as well. 
3. A variant racial trait for humans only, and a "generic" racial trait for all the other PC races from the PHB, SCAG and VGtM - if necessary, this can be extended to other races in the UA articles or any homebrew options. 

This should get things more in-line with the spirit of the article and allow racial feats to be valid for revenants. I'm merging the changes in today (12/19/2017), and will close this ticket. 

I did test the UA Feat Grudge-bearer on a Dwarf with the revenant subrace, this will work on most of the racial feats except for where they are narrowed down by subrace (like Fey Teleportation is locked to High Elf only - so no misty stepping revenant elves....).

**Comment by kjbro** [comment]
The new Revenant appears to have a couple bugs to work out:

-There are now two entries for Tiefling (core and community), similar to Aasimar, this is likely intentional.  However, the core Tiefling is broken, as Revenant is a subrace rather than a variant, and is the only subrace option, and if subrace options exist they must be selected.  So all core Tieflings now register as illegal unless they are revenants. 
-Dragonborn Revenant does not match the UA document (should have +1 str, +1 cha, +1 con.  Still has +2 str +1 cha)

Less a bug, more an observation:
-The new generic Revenant Variant Trait seems to be...inaccurate?...for any race which did not originally have subtypes or subraces, as it adds Revenant abilities and +1 con without removing anything from any race it is applied to.  I don't see an easy fix to this, as I don't think variant racial traits can be scripted with the complexity to determine and remove a secondary bonus for their race on the fly, let alone racial features?
