### ISSUE TITLE
Feat: Spell Sniper

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#72]
Is counting cantrips as .5 levels of spells and telling me to take 2 spells. When it should be one according to the PHB. Also giving me an error of Languages underspent: 0 of 0

![capture](https://cloud.githubusercontent.com/assets/17392134/13281293/372e2d88-daa0-11e5-9d8e-44779386b378.JPG)

**Comment by Sklore** [comment]
@shadowchemosh 

Might need your help here. Ideally the code below needs to have abValue5 changed to 0.5. However that change results in the Spell Snips tab not loading at all. 

I have no idea where the language requirement is coming from however when you fulfill the spell level requirement the language requirement fulfills also. 

```
      ~ Set the total number of spells allowed (ie 2 which is .5 for each
      ~ cantrip and 1 for 1st level spell).
      hero.childfound[cfg5CSpeSn].field[cfgMaxSp1].value += field[abValue5].value
```

**Comment by shadowchemosh** [comment]
Will take a look later. I am wondering if that "Language" issue is a LW bug as it was not doing that before 1.2 of 5e...

**Comment by shadowchemosh** [comment]
The language issue is a LW bug actually.  The .5 cantrip issue is caused by the Helper.SpCountLev tag I had on the configurable.  Helper.SpCountLev causes the configurable to count "levels" of the spells instead of a simple 1 to 1 relationship.  By removing Helper.SpCountLev and setting the spells allowed to 1 we get the effect we want of selecting a single cantrip.  

I will put in a bug report about the Language issue to LW.
