### ISSUE TITLE
Beast Master Ranger unable to add animal familiar

### ISSUE THREAD

**Issue by andr3w1sh** [Sklore/HL_DD_5e_Colab#726]
Just as the title states, if you choose the Beast Master archetype for Ranger, it does not allow you to add an animal companion. You have to create a new NPC hero.

**Comment by dungeonguru** [comment]
I looked at this and I think we need to add cHelpAnim to the Ranger's Companion ability. The problem I found is that it adds CR 0.5 and below and not 0.25 and below beasts.  I'm not sure why because the animal companion code looks right. Anyone else can comment?

**Comment by dungeonguru** [comment]
OK, I have added some code to address with a new Ranger's Companion companion in. I have gotten the creatures and attached minion to show up, and the bonuses to AC, attack/damage, and saving throws work, but the hit point maximum is still a manual adjustment on the minion since I'm not sure the wording is clear on whether the new hit point maximum grants any additional Hit Dice or simply raises the hit point maximum.
