### ISSUE TITLE
Wizard Illusion School and Minor Illusion Cantrip

### ISSUE THREAD

**Issue by Conandy1970** [Sklore/HL_DD_5e_Colab#732]
When rolling a wizard, if that character starts out level 1 with the Minor Illusion cantrip (either as one of his first 3 cantrips at level one, or as racial ability as a Forest Gnome), Hero Lab just gives him another copy of the same cantrip when he chooses his Illusion Arcane Tradition at level 2, instead of giving him a choice of another cantrip.  

In the Gnome version scenario, at level 2 he ends up with two copies of Minor Illusion under "Racial Spells & Spell-Like Abilities". 

In the wizard scenario with MI as one of his first 3 cantrips, at level 2 he just gets Minor Illusion added under "Racial Spells & Spell-Like Abilities". 

In both of these scenarios, he should get to choose a new cantrip instead.

**Comment by dungeonguru** [comment]
So, both scenarios (1 is not really broken, the other is)

1. non-forest gnome wizard picks the minor illusion cantrip at 1st level, then chooses school of illusion at 2nd. You'll see that the minor illusion cantrip is now both in the Known Cantrips on the _Wizard Spell ta_b *and* the _Racial Spells & Spell-like Abilities_ section on the _Spells tab_. If you go back to the _Wizard Spell_ tab, you can remove the duplicate cantrip and replace it with another. If you go back to the _Spells tab_, you'll see that minor illusion still shows up under the Racial & Spell-like section. Hero Lab allows you to remove the minor illusion cantrip and relearn another, but keeps the minor illusion as the spell-like ability. 

2. forest gnome gets minor illusion cantrip for being able to breathe. As a 1st level wizard, the gnome player should choose 3 other cantrips (never choose a cantrip you know for being a gnome anyway). Effectively a gnome wizard has 4 cantrips at 1st level, which are shown on the Spells tab. At 2nd level wizard, the school of illusion grants the minor illusion cantrip. This is currently putting a 2nd minor illusion cantrip into the racial/spell-like spells, rather than bumping up the number of cantrips known by 1. 

It may take some time to adjust the code for a forest gnome illusionist to get an extra cantrip as a 2nd level wizard (illusionist) since that is a very specific case of over-riding the normal logic.

**Comment by Conandy1970** [comment]
Thanks.  This is minor, I know.  I just added the extra cantrip with an Adjustment (my player has scenario 2).  But I do get tired of  constantly seeing the error that tells me he has too many cantrips.   I keep thinking I did something wrong. :)

**Comment by dungeonguru** [comment]
Added some code to the improved minor illusion special ability. If you have the Natural Illusionist (hence Forest Gnome), it adds 1 more cantrip slot, so you can learn it. Should go out in next push. 

Reference merge #738
