### ISSUE TITLE
Monster Manual: Replace Missing Monsters

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#76]
The following need to be added:

If you have added one of these monsters please comment below with a link to the file to speed up the process of completing this. 

**Missing Monsters:** 109
Completed:** 109 
**% Complete:** 100%

**Completed:**
**1.2:** _14 monsters_
Beholder - Added to *.stock
Death Tyrant - Added to *.stock
Spectator - Added to *.stock
Needle Blight - Added to *.stock
Twig Blight - Added to *.stock
Vine Blight - Added to *.stock
Pixie - Added to *.stock
Hook Horror - Added to *.stock
Kenku - Added to *.stock
Quaggoth - Added to *.stock
Myconid Sprout - Added to *.stock
Myconid Adult - Added to *.stock
Myconid Sovereign - Added to *.stock
Piercer - Added to *.stock

**1.3:** _95 monsters_
Aarakocra - Added to *.stock
Banshee - Added to *.stock
Bugbear Chief - Added to *.stock
Bullywug - Added to *.stock
Cambion - Added to *.stock
Carrion Crawler - Added to *.stock
Crawling Claw - Added to *.stock
Cyclops - Added to *.stock
Death Knight - Added to *.stock Note: Spits error if longsword is used 2H
Demilich - Added to *.stock
Demon (Barlgura) - Added to *.stock
Demon (Chasme) - Added to *.stock
Demon (Goristro) - Added to *.stock
Demon (Manes) - Added to *.stock
Demon (Shadow Demon) - Added to *.stock
Demon (Yochlol) - Added to *.stock
Dinosaur (Allosaurus) - Added to *.stock
Dinosaur (Ankylosaurus) - Added to *.stock
Dinosaur (Pteranodon) - Added to *.stock
Devil (Spined Devil) - Added to *.stock
Displacer Beast - Added to *.stock
Drow Elite Warrior - Added to *.stock
Drow Mage - Added to *.stock
Drow Priestess of Lolth - Added to *.stock
Monodrone - Added to *.stock
Duodrone - Added to *.stock
Tridrone - Added to *.stock
Quadrone - Added to *.stock
Pentadrone - Added to *.stock
Empyrean - Added to *.stock
Faerie Dragon (6 colors) - Added to *.stock
Flameskull - Added to *.stock
Flumph - Added to *.stock
Fomorian - Added to *.stock
Fungi (Gas Spore) - Added to *.stock
Galeb Duhr - Added to *.stock
Genie (Dao) - Added to *.stock
Genie (Marid) - Added to *.stock
Githyanki Warrior - Added to *.stock
Githyanki Knight - Added to *.stock
Githzerai Monk - Added to *.stock
Githzerai Zerth - Added to *.stock
Gnoll Pack Lord - Added to *.stock
Gnoll Fang of Yeenoghu - Added to *.stock
Goblin Boss - Added to *.stock
Grell - Added to *.stock
Grick Alpha - Added to *.stock
Half-Ogre - Added to *.stock
Helmed Horror - Added to *.stock
Hobgoblin Captain - Added to *.stock
Hobgoblin Warlord - Added to *.stock
Intellect Devourer - Added to *.stock
Jackalwere - Added to *.stock
Kobold (Winged) - Added to *.stock
Kuo-Toa - Added to *.stock
Kuo-Toa (Archpriest) - Added to *.stock
Kuo-Toa (Whip) - Added to *.stock
Lizardfolk (Shaman) - Added to *.stock
Lizardfolk (King/Queen)  - Added to *.stock
Mephit (Mud) - Added to *.stock
Mephit (Smoke) - Added to *.stock
Mind Flayer (still some bugs needs LW) - Added to *.stock
Bone Naga (2 types) - Added to *.stock
Nothic - Added to *.stock
Orc War Chief - Added to *.stock
Orc Eye of Gruumsh - Added to *.stock
Orog - Added to *.stock
Peryton - Added to *.stock
Quaggoth Spore Servant - Added to *.stock
Young Remorhaz - Added to *.stock
Revenant - Added to *.stock
Fire Snake - Added to *.stock
Sahuagin Priestess - Added to *.stock
Sahuagin Baron - Added to *.stock
Scarecrow - Added to *.stock
Slaad Tadpole - Added to *.stock
Red Slaad - Added to *.stock
Blue Slaad - Added to *.stock
Green Slaad - Added to *.stock
Gray Slaad - Added to *.stock
Death Slaad - Added to *.stock
Thri-kreen - Added to *.stock
Troglodyte - Added to *.stock
Umber Hulk - Added to *.stock
Water Weird - Added to *.stock
Yeti - Added to *.stock
Abominable Yeti  - Added to *.stock
Yuan-Ti Abomination - Added to *.stock
Yuan-Ti Malison (3 Types) - Added to *.stock
Yuan-ti Pureblood - Added to *.stock
Arcanaloth - Added to *.stock
Mezzoloth - Added to *.stock
Nycaloth - Added to *.stock
Ultroloth - Added to *.stock
Beholder Zombie - Added to *.stock

**Initial Creation Complete, Testing, Attacks and Special Abilities Required**
Dracolich (Adult Blue) (is template)
Dragon, Shadow (Young Red) (is template)

**Comment by Sklore** [comment]
Going to focus my effort on finishing the Monster Parser. This is too many to enter manually efficiently unless we get 150 community members to submit two each.

**Comment by shadowchemosh** [comment]
If you need help with specific abilities the monsters have I am happy to help script them.  But I simply don't have time to do mass data entry.  If I did I should do that for Pathfinder adventures. =)

Just an FYI is all...

**Comment by Sklore** [comment]
Oh the help wasnt aimed at you. This is a community pack so just trying to encourage some community involvement 😜

**Comment by Sklore** [comment]
If anyone wants to have a look at the following and call out any errors they can find with the base stats of the Monsters. I have not tried to add the Special Abilities / Attacks yet but I have managed to get the creation of the base stat block down to a few seconds per monster. Just need to get some fresh eyes over them before I start punching these out in bulk. 

- Aarakocra
- Banshee
- Bugbear Chief
- Bullywug

The following things should be working:

- ThingId
- Name
- Hit Dice #
- Dice Sides
- Default HP
- Speed
- STR, DEX, CON, INT, WIS, CHA
- Challenge Rating
- Source Name
- Alignment
- Size
- Skill Proficiency
- Damage Resistance
- Damage Vulnerability
- Damage Immunity
- Condition Immunity
- Languages
- Type
- Flight
- Blindsight
- Dakvision
- Telepathy

**Comment by Sklore** [comment]
Link to the tool in case anyone is interested. 

https://www.dropbox.com/s/2j0m5nzcxfay8h5/5C%20Parser%20-%20Hero%20Labs.xlsx?dl=0

**Comment by grandchefpanda** [comment]
Some of the monsters from your list are in the SRD. I think I have read somewhere on the herolab forum that the missing monsters from the SRD will be released with the Encounter Builder and Monster Builder early March.
http://forums.wolflair.com/showthread.php?t=55125

**Comment by grandchefpanda** [comment]
Look like all NPC are in the SRD 1.1. I'm expecting LWD to release them with next release too.

**Comment by grandchefpanda** [comment]
As are all animals

**Comment by Sklore** [comment]
Music to my ears!

**Comment by Sklore** [comment]
Ok moving this list to here in case i need it in the future and updating the list above with the original SRD missing list. 

Pending
Cambion
Carrion Crawler
Crawling Claw
Cyclops
Death Knight
Demilich
Demon (Barlgura)
Demon (Chasme)
Demon (Goristro)
Demon (Manes)
Demon (Shadow Demon)
Demon (Yochlol)
Spined Devil
Dinosaur (Allosaurus)
Dinosaur (Ankylosaurus)
Dinosaur (Pteranodon)
Displacer Beast
Dracolich (Adult Blue)
Drow
Drow Elite Warrior
Drow Mage
Drow Priestess of Lolth
Empyrean
Faerie Dragon
Flameskull
Flumph
Fomorian
Fungi (Gas Spore)
Galeb Duhr
Githyanki
Genie (Dao)
Genie (Marid)
Githyanki Warrior
Githyanki Knight
Githzerai Monk
Githzerai Zerth
Gnoll Pack Lord
Gnoll Fang of Yeenoghu
Goblin Boss
Grell
Grick Alpha
Half-Red Dragon Veteran
Helmed Horror
Hobgoblin Captain
Hobgoblin Warlord
Hook Horror
Intellect Devourer
Jackalwere
Kenku
Kobold (Winged)
Kraken
Kuo-Toa
Kuo-Toa (Archpriest)
Kuo-Toa (Whip)
Lamia
Lich
Lizardfolk
Lizardfolk (Shaman)
Lizardfolk (King/Queen)
Werebear
Wereboar
Wererat
Weretiger
Werewolf
Magmin
Manticore
Medusa
Mephit (Dust)
Mephit (Ice)
Mephit (Magma)
Mephit (Mud)
Mephit (Smoke)
Mephit (Steam)
Merfolk
Merrow
Mimic
Mind Flayer
Minotaur
Modrone
Duodrone
Tridrone
Quadrone
Pentadrone
Mummy
Mummy Lord
Myconid Sprout
Quaggoth Spore Servant
Myconid Adult
Myconid Sovereign
Bone Naga
Spirit Naga
Guardian Naga
Nightmare
Nothic
Ogre
Half-Ogre
Oni
Black Pudding
Gelatinous Cube
Gray Ooze
Ochre Jelly
Orc
Orc War Chief
Orc Eye of Gruumsh
Orog
Otyugh
Owlbear
Pegasus
Peryton
Piercer
Pixie
Pseudodragon
Purple Worm
Quaggoth
Rakshasa
Remorhaz
Young Remorhaz
Revenant
Roc
Roper
Rust Monster
Sahuagin
Sahuagin Priestess
Sahuagin Baron
Fire Snake
Salamander
Satyr
Scarecrow
Shadow
Shambling Mound
Shield Guardian
Skeletons
Minotaur Skeleton
Warhorse Skeleton
Sladd Tadpole
Red Slaad
Blue Slaad
Green Slaad
Gray Slaad
Death Slaad
Specter
Androsphinx
Gynosphynx
Sprite
Stirge
Succubus / Incubus
Tarrasque
Thri-kreen
Treant
Troglodyte
Trolls
Umber Hulk
Unicorn
Vampire
Vampire Spawn
Water Weird
Wight
Will-o'-Wisp
Wraith
Wyvern
Xorn
Yeti
Abominable Yeti 
Yuan-Ti Abomination
Yuan-Ti Malison
Yuan-Ti Pureblood
Arcanaloth
Mezzoloth
Nycaloth
Ultroloth
Zombie
Ogre Zombie
Beholder Zombie
Ape
Awakened Shrub
Awakened Tree
Axe Beak
Baboon
Badger
Black Bear
Blink Dog
Blood Hawj
Boar
Brown Bear
Camel
Constrictor Snake
Crab
Crocodile
Death Dog
Deer
Dire Wolf
Draft Horse
Eagle
Elephant 
Elk
Flying Snake
Frog
Giant Ape
Giant Badger
Giant Bat
Giant Boar
Giant Centipede
Giant Constrictor Snake
Giant Crab
Giant Crocodile
Giant Eagle
Giant Elk
Giant Fire Beetle
Giant Frog
Giant Goat
Giant Hyena
Giant Lizard
Giant Octopus
Giant Owl
Giant Poisonous Snake
Giant Rat
Giant Scorpion
Giant Sea Horse
Giant Shark
Giant Spider
Giant Toad
Giant Vulture
Giant Wasp
Giant Weasel
Giant Wolf Spider
Goat
Hunter Shark
Hyena
Jackal
Killer Whale
Lion
Lizard
Mammoth
Mastiff
Octopus 
Owl
Phase Spider
Polar Bear
Pony
Quipper
Reef Shark
Rhinoceros
Riding Horse
Saber-Toothed Tiger
Scorpion
Sea Horse
Spider
Swarm of Bats
Swarm of Insects
Swarm of Beetles
Swarm of Centipedes
Swarm of Spiders
Swarm of Wasps
Swarm of Poisonous Snakes
Swarm of Quippers
Swarm of Rats
Swarm of Ravens
Tiger
Vulture
Weasel
Winter WolfWolf
Worg
Acolyte
Archmage
Assassin
Bandit
Bandit Captain
Berserker
Commoner
Cultist
Cult Fanatic
Druid
Gladiator
Guard
Knight
Mage
Noble
Priest
Scout
Spy
Thug
Tribal Warrior
Veteran

**Comment by Sklore** [comment]
Yup i prefer the new list.

**Comment by grandchefpanda** [comment]
Just for info, the drow is already in herolab except it is ordered as elf, drow

**Comment by Sklore** [comment]
Thank you

**Comment by grandchefpanda** [comment]
Pixie is complete , also some fixes #109

**Comment by grandchefpanda** [comment]
For your info, the Pixie was missing his Dice Sides, Type and Alignment

**Comment by Sklore** [comment]
Yeah the source i used was pretty bad so there will be bits missing and things wrong. They will all need to be individually checked and confirmed. Figured this is just a good starting point to help speed the process along.

**Comment by Sklore** [comment]
I can also start on parsing all the special abilities in if we think that will help. They would all be added in as a text only special ability for now and need to be manually linked to monsters and then adjusted for any damage rolls etc.

**Comment by grandchefpanda** [comment]
A lot of abilities like magic resistance etc already exist on other monsters, a simple copy and some changes in the text and it's done. The manually linking will be confusing. So my opinion is that will help in some cases and be counter productive on others and I personally prefer to do things one at a time now that the basic is in there. Your call ^^

I will try to complete some other monsters today.

**Comment by Sklore** [comment]
:+1: sounds like a plan. If we can get a few of us doing this one monster at a time it shouldn't take long anyway.

**Comment by grandchefpanda** [comment]
What about variant monsters (each drow, the quaggoth etc have variant), should we create entry for them too ?

**Comment by grandchefpanda** [comment]
Can you check the Pixie, it has a proficiency of +2 and +2 WIS but the skill perception shows +6 instead of +4. It show the calcul of  +4 proficiency +2 WIS. Is it a bug or did I do something wrong, can't tell ?

**Comment by grandchefpanda** [comment]
Found, there is an evalscript on all monster you created that double the perception proficiency. Will have to remove them. Then if I add the skills the monster is proficient with, the values become correct. Will merge later

**Comment by shadowchemosh** [comment]
FYI guys.  Racial Specials, Abilities, Class Abilities should not actually be 'Source' marked.  It will cause you problems later when you want to reuse something from say MM1 for a MM2 monster.  Anything that is only displayed by being 'bootstrapped' to a monster/class should not be source marked.

Second thing is that I would advise breaking up the "Races" from the Special Abilities into two different files.  It makes for doing mass fixes very easy.  In example if all the Special Abilities where in one .user file separate from the races you could easily do a Find/Replace to remove all the sources that got added.

I am just mentioning things from experience with the other community Packs is all.  Feel free to ignore or not as much as you like. =)

Last note Because "Abilities" are not source marked what I did in Pathfinder was use the 'Product ID' to mark everything to the 'Community' so its easy to tell when someone does a "New copy" that they got a community Thing.

**Comment by grandchefpanda** [comment]
#113 Added the Hook Horror, difficult one  ^^
Also change the source as @shadowchemosh suggested

**Comment by shadowchemosh** [comment]
So this maybe a "stupid" comment or piece of information.  Mostly as I don't know how exactly 5e monsters are put together.

For example the "Elf, Drow Priestess Of Lolth" race that was entered.  Is this "really" a different "elf" or does it just have different "Stats" than a normal Drow (ie different Ability scores and different class)?

I ask because in 3.5 days a Drow was a Drow and you would make a Drow "race" in the editor.  But then you would build the Drow "characters" using HL normally.  This would allow you change ability scores, skill points, feat, classes, spells, and weapons.  You could make a Rogue drow and a cleric drow etc.  Then you would "save" this as a normal .por file.  After you created a bunch of "Drow" you would then make a ".stock" file called "Drow.stock" and do a "Portfolio->Import Hero from Portfolio" and combine all the Drow's into one .stock files.

These .stock files are then placed in the same location as .user files and that is what the "Gamemaster->Show Encounter Builder" actually reads.  This allows GM's to pull in different "monsters" all stated up just like the books into a HL encounter file and adjust them as they wish.

Again I ONLY mention this based on other versions of DnD and maybe that is NOT at all how monsters work in 5e.  In which case feel free to point and laugh at me. =)  But before you guys get too far I wanted to "mention" the above.......

**Comment by Sklore** [comment]
I was pondering on this. Technically there are different variants that go up in challenge levels. Given the way it works as just a race though I think your right, you could just add classes and mod the stats as you please. Could be an interesting concept allowing for some great customization. 

@grandchefpanda I added the bootstrap for the perception on purpose. I figure its easier to delete a bootstrap than it is to search and add one back in.

**Comment by grandchefpanda** [comment]
There is a guideline in the DMG about modifying and creating monsters, but it is completely different than player characters and than Pathfinder, they say it is simplified but I find it less clear. You can also add class to a monster but usually you just change the stats and recalculate the CR with the table of page 274 of the DMG, based on defensive and offensive CR. Ideally HL should allow us to change NPC as we wish and calculate the CR for us ... for now this is by creating a race in the editor... so yes we need to create them until HL find a better way to handle this. I'm waiting for the next release of the SRD with the encounter editor to see where they are going. It would be easier to do in a NPC sheet fillable and by drag and droping abilities and spells.

**Comment by grandchefpanda** [comment]
Some kind of NPC creator ^^

**Comment by grandchefpanda** [comment]
Kenku is done, the non natural weapons are not in the race so they where left out but checked the value where correct in the statblock if added. #121

**Comment by grandchefpanda** [comment]
Quaggoth is done

**Comment by grandchefpanda** [comment]
Added Myconids Sprout, Adult and Sovereign
Still bugs in Piercer #134

**Comment by grandchefpanda** [comment]
Cyclops done, wait for 1.3

**Comment by grandchefpanda** [comment]
For the drows, we need to wait for the NPC from LW to see how they will implement spellcasters. all monsters and npc with spellcasting are missing for now.

**Comment by grandchefpanda** [comment]
Cyclops lost when installing 1.2 ... need to redo it, should have done a commit... next time

**Comment by grandchefpanda** [comment]
Cyclops #138

**Comment by shadowchemosh** [comment]
Sorry... =(

**Comment by shadowchemosh** [comment]
As you guys are entering monsters have you seen "similar" abilities popping up?  In Pathfinder we find allot of abilities are similar especially when it deals with Poison, Diseases, or Breath Weapons.  Those last three all just have "minor" tweaks of being different.

What we ended up doing was making a Single Helper Things for the above that used "Tags/Values" to allow for setting the slight differences on each monster.  This especially true for Breath Weapon because I got sick of seeing the 500 Breath Weapon racial specials that only difference was the "size" and elemental type. =(

Just again a mention that its worth to make abilities that basically the same into a single Thing.  You can then just "Bootstrap" the correct ability onto your race and not have to make a new Ability for each monster.  This is especially true if the only difference is using the "monsters" name in the ability.

In example the text "The cyclops has disadvantage on any attack roll against a target more than 30 feet away." could become "This creature has disadvantage on any attack roll against a target more than 30 feet away.".

Or change the text to "This creature has disadvantage on any attack roll against a target some distance away."  Then have the field abSumm (abSumm) be set with the amount of distance based on a Value.? tag or abValue field using a script.  Then set the value when you bootstrap the ability to the race.  abSumm is the value that is actually displayed on the Summary Tab and should be the one that goes to the statblock.

This is just an "example" as it makes future monsters go faster and allows for "reusable ability" of code.  Plus lowers future maintenance as less Things to maintain.

Just some things to think about as you enter monsters...

**Comment by grandchefpanda** [comment]
For now I'm doing like LW has been doing for monsters from the SRD, do a lot of copy like you said, it help me understand Herolab too.
Could this been changed later, I already have difficulties to organize everything in my mind already, so it is for now easier to simply do duplicate, but later (when all monsters from the MM are done) I could check what are the duplicate abilities from our pack and put them together with a script like you explain. 
Normally these abilities will only be added as bootstraps, so if my understanding is correct, we can safely remove them. Am I right or should we proceed like you explain. I can also if I find a duplicate when creating a new monster convert the existing ability to a dynamic one.

**Comment by Sklore** [comment]
It won't cause any harm to proceed the way you are going. 

From a coding perspective shadows way will result in less code and smaller file size.

**Comment by grandchefpanda** [comment]
But can we change this later, at the end of the creation of the MM missing monsters, we will see the duplicates then we can change them to optimize. I also like to optimize ;-)

**Comment by shadowchemosh** [comment]
If you remove a bootstrapped "Thing" later on it can cause any existing portfolio's to give an "error" message about the missing Thing.  This is easily fixed by dirtying up the .por file and saving it again but will freak out some users. =(

For monsters that will eventually I assume go into .stock files (and released to the community) HL has a feature that I requested be added that lets you do a "Mass" re-save of .por/.stock files.  This helps as for Pathfinder I am currently over 1.5gigs of por/encounter files.

As Sklore says it will not hurt to go the way your going.  My programmer side likes "re-usable" objects much more. =)  And again this is your guys project I am just sort of like a "Consultant" giving advice.  I am not going to be offended if you don't take it.  Just giving some thoughts on what I have seen.  This issue I ran into in Pathfinder was that LW created 50+ Breath Weapons and like 25 abilities named "Frenzy".  The issue being the only difference was the "monsters" name.  But then we had feats that required the racial Special "Frenzy" as a pre-req and how do you check for that when you have 25 different Unique ID's and each new Monster book added more???  To me it made things a mess a un-needed objects and part of the reason Pathfinder download is almost 200 megs... =(

The big missing feature from HL would be simple replacement characters.  So that you could have the sentence be **The ##MONSTER## has disadvantage on any attack roll against a target more than ##VALUE## feet away**.  Then have the ##MONSTER## value be auto replaced with the name of the monster its bootstrapped too.  Maybe someday...

**Comment by grandchefpanda** [comment]
#140 Yeti and Abominable Yeti added

@shadowchemosh I have implemented a script to change the description of Chilling Gaze so it uses the same Race Ability for both Yeti and Abominable Yeti. It uses abText and abValue variable, can you check if this is the right way to go ? also, I think there must be a way to use the calculated value of the DC abSave.aCON to get the value of the DC, now it uses abValue.

**Comment by shadowchemosh** [comment]
The DC is stored in the field abDC to access just do **field[abDC].value** which is being auto-calculated on the racial special.  So just replace the abValue logic with that and you should be good to go.

The "short" description you see on the "Summary" tab by the way is stored in the field[abSumm].text  So you could change it also if you want as so:

`field[abSumm].text = "The yeti targets one creature it can see within " & field[abValue].value & "ft."
`
Otherwise yeah it looks really good actually grandchefpanda.  A reusable Racial Special very nice! =)

I have to laugh as I already looked at the added Racial Specials LW did and already almost two dozen "breath weapons".  At least a dozen "Amphibious" racial specials also.... Sigh....

**Comment by grandchefpanda** [comment]
Thanks it works.
I will test now if I can do the same thing to Myconids and if I can remove/hide/obsolete the Race double and triple feature. So I will save a portfolio with myconids as they are now and then use one dynamic racial ability for them all and load again the portfolio with the removed abilities to see if there are warnings etc. in herolab. If not then it will be safe.

**Comment by grandchefpanda** [comment]
#147 Tested with myconids if we could merge multiple racial abilities into one with scripts without causing problems with already existing portfolios, it works so I merged the Myconids Racial abilities that where similar.

**Comment by grandchefpanda** [comment]
Added Thri-kreen #149

**Comment by grandchefpanda** [comment]
Troglodyte done

**Comment by Sklore** [comment]
Mate your on fire. I'm currently bouncing between holding a screaming baby and playing Mrs Rabbit in the chronicles of "in sick to death of peppa pig".

**Comment by grandchefpanda** [comment]
I have nothing planned yet for tomorrow ^^, I feel like doing a lot of monsters

**Comment by grandchefpanda** [comment]
#158 I change a few Racial abilities so we can display the monster name like in the MM.

**Comment by grandchefpanda** [comment]
Spined devil and dinosaurs done

**Comment by grandchefpanda** [comment]
I'll do Displacer beast and drows next

**Comment by grandchefpanda** [comment]
Small change to death knight

**Comment by grandchefpanda** [comment]
Displacer beast and drow elite warrior done #162

**Comment by grandchefpanda** [comment]
Monodrone, Duodrone, Tridrone, Quadrone, Pentadrone #169

**Comment by grandchefpanda** [comment]
#179 Drow Mage and Drow Priestess of Lolth (no spellcasting)

**Comment by grandchefpanda** [comment]
#182 Scarecrow

**Comment by grandchefpanda** [comment]
Half Ogre + Water Weird

**Comment by grandchefpanda** [comment]
I'm currently checking which monsters are in which supplement, variant monsters, Adventure League, etc

**Comment by grandchefpanda** [comment]
Slaad Tadpole
Red Slaad
Blue Slaad
Green Slaad
Gray Slaad
Death Slaad

**Comment by grandchefpanda** [comment]
All Demons done #201

**Comment by grandchefpanda** [comment]
Winged Kobold + Helmed horror

**Comment by grandchefpanda** [comment]
#214 Goblins and Hobgoblins

**Comment by grandchefpanda** [comment]
Added Arcanaloth, Mezzoloth, Nycaloth, Ultroloth to the list of TODO

**Comment by grandchefpanda** [comment]
Added Remoratz and Orcs #215

**Comment by grandchefpanda** [comment]
#222 Flumph and Flame Skull (with errata)

**Comment by grandchefpanda** [comment]
#232 
Githyanki Warrior
Githyanki Knight
Githzerai Monk
Githzerai Zerth

**Comment by grandchefpanda** [comment]
1.3 is out with enhancements I asked, I'll implement the 8 missing monsters and all spellcasting abilities tomorrow.

**Comment by Sklore** [comment]
Once these are all done I'm assuming we need to release with a *.source file also. Anyone know how to do this? Ideally we should try and include pictures for all the monsters. That would be cool. But we would need to be incredibly careful to pick images that are free to use if we go down that road. 

http://forums.wolflair.com/showthread.php?t=55402

Again Panda, thanks! Your work on these has been incredible. We could do with some more people with your scripting ability!

**Comment by Sklore** [comment]
Stock file looks pretty easy to make, I'll start creating something now.

**Comment by Sklore** [comment]
Spells are so easy to add now :)

**Comment by shadowchemosh** [comment]
Nice!

Based on what I have seen for LW and stuff may want to do something like monsters A-C in one stock file and D-F in another.  Just because you get too many monsters in a single .stock file and it tends to really slow HL down.  In addition the encounter builder software does not care if we have 1 .stock file or 500....

**Comment by Sklore** [comment]
Ok, i was wondering why they had done it. I was going with the theory that they assigned different people to different monsters ;)

Think I've found an error with the Monster Manual. Death Knight is listed as knowing the Hold Person spell (3rd level). He's a lvl 19 Paladin caster. Problem is Hold Person is not actually a Paladin spell. If there a way for me to Bootstrap the spell as an extra lvl 3 spell? I know how to add it as a racial extra but that's not really the same.

**Comment by shadowchemosh** [comment]
This will be the fun part based on what Sklore just found.  Had lots of talk about this when we did Pathfinder.  You are going to find LOTS of statblock errors like the no Hold Person spell.  Do you a) mock it up to match the statblock or b) leave it correct and don't pick the spell?

If you are going to mock it up its where the "Adjustments" come in really handy.  Does 5e have one for adding a spell to classes spell list?

**Comment by Sklore** [comment]
There are 3 spell related adjustments. 

Add Spell Type to Class - Add entire spell list to a class
Change Spell Attribute - Change your spell casting attribute
Casting Attribute - Change which attribute a class used for its spellcasting. 

Add Spell Type to Class should work in this situation however i dont think its working. The first drop down works but the second just lists no selection.

**Comment by shadowchemosh** [comment]
Well that's not a very useful adjustment. =)  Another LW bug report...

**Comment by shadowchemosh** [comment]
So testing quickly that adjustment works for me.  Did you add 19 levels of Paladin?

**Comment by Sklore** [comment]
no i didnt. Wont that add a whole heap of stuff to the monster that shouldnt be there?

**Comment by shadowchemosh** [comment]
I guess thats a confusion between Pathfinder and 5e then?  In Pathfinder a creature that is a 19th level Paladin gets all the paladin abilities.  Just like any race taking class levels.

If 5e is different then whats the reference to the 19th Paladin?  Or is that ONLY spells?

**Comment by Sklore** [comment]
Here's an example. The level really only applies to the spells. 

![2016-03-24 12_31_55-monsters manual 5e pdf - adobe acrobat pro dc](https://cloud.githubusercontent.com/assets/8046697/14006363/7e988f6e-f1bc-11e5-8a81-721ae1df896e.png)

**Comment by shadowchemosh** [comment]
Ok.  So I see said the blind man to his deaf dog about his retarded son!

Based on what I am seeing in the main for "Death Knight" the "Spellcasting" part of the race is not setup.

![deathknight](https://cloud.githubusercontent.com/assets/7717785/14006437/39a6c9ce-f13b-11e5-8291-e27f8e86a4b4.jpg)

Once added that does not solve the issue of the spell (Hold Person).  Those current adjustments and the one I added is ONLY going to work with classes.  Which this has 'Racial Spells'.  Let me see if I can add an adjustment for Racial Spells...

**Comment by Sklore** [comment]
:+1:  And your right. I'm finding alot more of these.

**Comment by Sklore** [comment]
I should mention that these spell options i'm filling in as I go through the list. This functionality is new in 1.3.

**Comment by shadowchemosh** [comment]
I suspect that was a new feature of 1.3.  Why it was not currently done.  I think I remember panda saying that at one point.

In other good news a very simple change to the adjustment I just added will allow it to work for Races or Classes.  Going to make that change.  Then you can use the adjustment to add one single spell of Hold Person to the Death Knight.

**Note:** You may wish to do that adjustment on the "Personal" tab instead as it really is a permanent change to match the statblock.  Then you could add a note to the "(source)" to say made to match statblock.

**Comment by grandchefpanda** [comment]
Yes, this is a new functionality of 1.3 and I was waiting for it. I'm on leave today so I will try to finish the monsters.

**Comment by grandchefpanda** [comment]
corrected the target for 3 monsters

**Comment by grandchefpanda** [comment]
There is a lot of statblock error still in the monster manual, some are corrected by the 1.1 errata but some are not, usually I have left the correct value but sometime not, depending of what I beleived to be the correct value.

**Comment by grandchefpanda** [comment]
Just discovered that there is a Double skill proficiency tags with new 1.3 SRD, we should remove the scripts and put tag instead

**Comment by grandchefpanda** [comment]
All monsters done, now I will add spellcasting to the one that miss it.

**Comment by grandchefpanda** [comment]
Then will create the dracolich and shadow template

**Comment by grandchefpanda** [comment]
For template, we need LW to do a template tab like in Pathfinder

**Comment by grandchefpanda** [comment]
All spellcasting done

**Comment by grandchefpanda** [comment]
100% complete #259

**Comment by shadowchemosh** [comment]
Just FYI the new equipment in the COM_5ePack_PHB - Monster.user file has equipment that is not source marked....

**Comment by grandchefpanda** [comment]
thnaks, I will mark them. Also I need to remove double skill prof scripts as since 1.3 SRD there is a tag for it. Also need to change the wAttackEff on monsters with DC value as there is mecanics for it to be dynamics, just discovered it when looking at the Dog creature.
