### ISSUE TITLE
Silence spell

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#78]
Silent spell is flagged as a Ritual, it is not.

**Comment by Sklore** [comment]
According to the PHB this is a Ritual spell. 

Silence - pg 275 of the PHB. 
2nd-level illusion (ritual)
Casting Time: 1 action
Range: 120 feet
Components: V, S
Duration: Concentration, up to 10 minutes

Checked Errata and confirmed this has not been changed. 

Please re-open this ticket with a link to the reference that states this is not meant to be a Ritual spell if my sources are wrong due to an official change I am not aware of.
