### ISSUE TITLE
Issues from Pull 779, related to Issue 715 (Revenants)

### ISSUE THREAD

**Issue by kjbro** [Sklore/HL_DD_5e_Colab#780]
Can't re-open 715, so I'm putting this here.  The new Revenant appears to have a couple bugs to work out:

-There are now two entries for Tiefling (core and community), similar to Aasimar, this is likely intentional. However, the core Tiefling is broken, as Revenant is a subrace rather than a variant, and is the only subrace option, and if subrace options exist they must be selected. So all core Tieflings now register as illegal unless they are revenants.
-Dragonborn Revenant does not match the UA document (should have +1 str, +1 cha, +1 con. Still has +2 str +1 cha)

Less a bug, more an observation:
-The new generic Revenant Variant Trait seems to be...inaccurate?...for any race which did not originally have subtypes or subraces, as it adds Revenant abilities and +1 con without removing anything from any race it is applied to. I don't see an easy fix to this, as I don't think variant racial traits can be scripted with the complexity to determine and remove a secondary bonus for their race on the fly, let alone racial features?

**Comment by dungeonguru** [comment]
OK, things that can be fixed before 2.2 is released to the public next year - 

1. The second tiefling is likely the one from the new "That Old Black Magic" and is there by design. I'll fix the tiefling error on the community tiefling. 
2. Good catch, I missed where I forgot to add the script adding the CON and removing 1 STR. I should get that fixed here soon. It was hard enough to craft the option as it looks now since the dragon ancestry is an oddity.

and 

3. the UA article itself just states that for races without a subrace: " you can apply this new subrace to a race without subrace options using the modification options provided below." This means they meant it to be a template (which is unavailable to PCs in HL), but the variant racial trait functions can easily add the +1 Con and Relentless Nature. If you're implying the +1 Con overwrites the base ability score modification of any race without a subrace (like half-elf, half-orc), we could easily do that, but simply adding +1 Con doesn't particularly imbalance anything in the game. 

And, my observation: This revenant is incomplete - I would suggest adding the Undead type tag and all that implies. I was hoping that Ravenloft was going to be expanded, and I still hope they come back to it again and fill in the blanks on character options like this.
