### ISSUE TITLE
Pathfinder-like spell adjustments

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#806]
An older ticket (#734) getting some attention again - a couple of folks have asked for pathfinder-like spell adjustments. Will probably need some help from shadowchemosh for some sense of how to tackle this large project.

**Comment by Fenris447** [comment]
@LordMorin in issue #853, you mentioned you have some adjustments for these already that need to be fixed to have the 5C coding. If you still have these, I’d be happy to make the changes and get them into the files. Just send them over!

**Comment by Fenris447** [comment]
I have a bunch done, including some AC adjustment spells and weapon-enhancing spells. I'm not going to do anything that can be achieved with a single Adjustment on its own. For instance, the Shield spell or Shield of Faith spell both are simple AC adds. There's already an adjustment to add a bonus to AC, so we don't need adjustments for that. On the other hand, there are things like Barkskin that sets a minimum AC. Rather than force the player to evaluate their AC and up it dynamically, there's a Barkskin adjustment that sets your AC to a maximum of your current or 16.

If anyone has any spells they want to see, post them here or [on this thread](http://forums.wolflair.com/showthread.php?t=65243). I won't guarantee anything, but I'm open to suggestions.

**Comment by Fenris447** [comment]
Added: Alter Self (Natural Weapons), Awaken, Barkskin, Darkvision, Elemental Weapon, Enhance Ability, Enlarge/Reduce, Guardian of Nature, Haste, Holy Weapon, Mage Armor, Magic Stone, Magic Weapon, Otherworldly Guise, Shadow Blade, Shillelagh, Skill Empowerment, Slow, and Transformation. I also am adding the Animated Object, Phantom Steed, and Tiny Servant to the encounter builder so players can add those creatures to their portfolio when summoned.

I'll leave this open until I'm wrapping up the release, in case anyone has spells to request or add.

**Comment by Fenris447** [comment]
Last call for suggestions. I'm wrapping up 3.1. We can always add more later, but I'd love to hit everything now.

**Comment by Fenris447** [comment]
I've asked ShadowChemosh to push 3.1 to everybody. So I'm closing this sucker down. If anyone comes up with more spells that need adjustments, they can always open new issues.
