### ISSUE TITLE
Question: Expanded Spell List

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#826]
Does anyone know if this is possible to code? Spells are generally hard coded upon creation. 

The Forest lets you choose from these additional spells when you learn a warlock spell. They are considered warlock spells for you.

Level Spells
1st entangle, fog cloud
2nd pass without trace, spike growth
3rd plant growth, speak with plants
4th dominate beast, phantasmal killer
5th dominate person, tree stride

**Comment by dungeonguru** [comment]
Generally speaking, when you create the warlock subclass you add the patron spells by adding the ClsAllowSp.XXXX tags to the subclass (where XXXX is the id of the spells, so on the tags selection for "The Forest" there should be a tag for Entangle that goes: ClsAllowSp.spEntangle .

Otherwise, ShadowChemosh has mentioned several times on the forums that you can extend tags to existing spells using the *Extend functions.  You can easily add sClass.cHelpWlk to those spells using extend.

**Comment by Sklore** [comment]
Doh I was way over thinking this. Thanks Dungeon. Should have just copied the Archfey.

**Comment by LordMorin** [comment]
That works too. :)
