### ISSUE TITLE
Hexblade (XGtE) Hex Warrior Bug

### ISSUE THREAD

**Issue by kjbro** [Sklore/HL_DD_5e_Colab#832]
Steps to reproduce:
Create a new character with at least 3 levels of warlock.
Select Hexblade and Pact of the Blade.
Add a magic weapon to the character (in my case, Flame Tongue Greatsword)
For Pact of the Blade, select the magic weapon from the dropdown.
Click the Hex Warrior dropdown.

What should happen:
The magic weapon appears as a valid option on the dropdown, and Hex Warrior is applied to the weapon.

What is happening:
The Hex Warrior dropdown appears to be filled with a great deal of gibberish.  If the actual magic weapon is selected from the list, or anything else is selected from the list, an error is received:  "Syntax error in dynamic 'candidate' tag expression".  

Notes:
-This does not appear to happen with non-magical weapons.
-This happened with several magic weapons during my testing, not just Flame Tongue.
-This only appears to happen for two-handed weapons.  Both magical and non-magical one-handed weapons worked correctly in my testing.  
-This appears to affect both melee and ranged two-handed weapons, as both greatsword and longbow produced the bug during my testing.

**Comment by dungeonguru** [comment]
I see the issue - in script 3 on Hex Warrior, the search string generated from the chosen weapon on Pact Weapon needs to change the list seperator from a "," to a "|" and enclose the search criteria in parentheses (new code example attached):

**Code:**
```
~ if a pact weapon is chosen that is two-handed, then have to manually
~ add it to the list of weapons
if ( hero.childfound[cWlkPacBla].field[usrChosen1].chosen.tagis[wProperty.TwoHanded] = 1 ) then
     searchexp = "(component.BaseWep & !wProperty.TwoHanded) | (" & hero.childfound[cWlkPacBla].field[usrChosen1].chosen.tagids[thingid.?,"|"] & ")"
endif
```
After one of the last patches, I believe that some of the magic weapons started pushing multiple thingids (1 for the base weapon and 1 for the magical item gizmo), this blew up because the "," character there now is not a valid search parameter. Will fix and put in next release.

**Comment by kjbro** [comment]
Added code change locally, appears to fix all test cases where I was seeing the bug before.  Thanks!
