### ISSUE TITLE
Able to help if needed

### ISSUE THREAD

**Issue by ehmitchell3** [Sklore/HL_DD_5e_Colab#839]
Feel free to let me know.

Thanks!

**Comment by Sklore** [comment]
Thanks! We are always open to new helpers!

What sort of experience do you have with the Hero Lab Editor? Need to get an idea of where you might be the most help.

**Comment by ehmitchell3** [comment]
Sklore/all,

I have tinkered with the editor, and have cloned and changed stuff, but I’d still consider myself a beginner.

Thanks!

**Comment by Sklore** [comment]
The one place we always need help with is the Issues. That's where we keep open tickets on new requests and faults. Any assistance you can offer there would be greatly appreciated. Some of them require coding knowledge which is where I struggle. 

When creating new things we need to ensure we don't keep any descriptive text in objects. We strip things back to just mechanics due to copyright limitations. 

Recommend you have a look through the content in the 5e pack if you would like to learn how to do things. The best way I've found is to learn from the examples of others. 

We use the 5C naming convention for everything. That needs to be in the name of every item wee put in the pack. 

Ultimately you are better contributing however you feel you can best contribute though. If you have some ideas of your strengths let me know and we can see what needs doing.

**Comment by dungeonguru** [comment]
@Sklore  - you might want to send your document on how to upload to github. 

Getting used to creating a branch to work in and then creating a pull request to merge into the master copy is a little hurdle that sometimes trips people up. It also allows us to track what changes happened when and links them to the issue worked. Dropping updated files directly into the master creates some problems of its own. 

The second hurdle is keeping the wiki for pending changes updated. If you work an issue and merge it into the master source repo you need to update this page: 
[https://github.com/Sklore/HL_DD_5e_Colab/wiki/3.-Pending-Changes](url)

We copy/paste this page into the release notes when we're ready for the release. 

Other than that, good luck and enjoy learning a lot. There are so many scripts that have been created, often you just need to copy and tweak something that exists already so don't worry too much about picking up scripting quickly. The easiest tasks are spells and monsters since these usually don't get scripts, the most complex tasks seem to be classes and subclasses; everything else falls in between.

**Comment by Sklore** [comment]
Good idea. Browsing over the wiki in its entirety could help really.  

https://github.com/Sklore/HL_DD_5e_Colab/wiki

The wiki is there for us to track anything we may find useful in the future. Tutorials or even just list's of unique IDs for specific lists. I use it all the time to save myself having to search back through old code trying to find something that works. 

This is how I upload changes to GitHub. It's very important that you create your own branch for changes and don't make modifications to the core code. It make's it so much easier to roll a change back if it has unforeseen consequences and is also used when we prepare a release. 

https://github.com/Sklore/HL_DD_5e_Colab/wiki/How-to-upload-your-changes-to-GitHub

The learning curve is high. So lean on us as you need it. If you can't find me on here you can always chat to me directly on Facebook. Always happy to help. Dungeon is the better coder by far while my strengths lie in the data entry.
