### ISSUE TITLE
Staff of the Adder: Snake Head Attack

### ISSUE THREAD

**Issue by shadowchemosh** [Sklore/HL_DD_5e_Colab#840]
The "**Staff of the Adder: Snake Head Attack**" thing id w5CStAdder located in file "COM_5ePack_DMG - Equipment.user" is not source marked. In addition it has no Weapon Proficiency tags (wProfReq.?) which causes it sort to the very bottom of the weapons list on the weapons tab.

I found this while researching a question on the forums. I would fix but I don't know what this item is suppose to be so just letting you guys know. =)

Thanks!

**Comment by ehmitchell3** [comment]
Ended up adding the "simple" proficiency required, and then the DMG beta for Sources.

I'm not sure if it's supposed to be versatile, as I think it's [technically classified as an item](https://roll20.net/compendium/dnd5e/Staff#content)....

**Comment by dungeonguru** [comment]
Usually the magic staff, rod and other gear items that can be used to make an attack have a second weapon "Helper Object" attached to them that represents the weapon attack functions. So when you equip and attune the staff, the optional attack should show up on the weapons page so that people  can see the attack action.  The only optional thing you might want to do is add the tag "IsWeapon.wQtrstaff" so that the Druid can use it. (requires attunement by a cleric, druid, or warlock) 
Druids don't have the simple weapon proficiency, so they need to be able to add their proficiency somehow and they can use the quarterstaff, which this resembles enough. Either that that or mark the always proficient checkmark.
