### ISSUE TITLE
Blood Hunter Version Outdated?

### ISSUE THREAD

**Issue by kakitahero** [Sklore/HL_DD_5e_Colab#859]
I apologize if this isn't the best way/place to bring this up; it's my first time addressing an issue. And before I even bring it up, I just want to say you guys are doing an awesome job with this. All your hard work is definitely appreciated.

My question is about the Blood Hunter (probably obvious from the title), specifically its Blood Curses. It looks like the version of the class being used in Hero Lab is this one:
https://geekandsundry.com/wp-content/uploads/2015/12/Blood-Hunter-Class-1.2.pdf
but the builder for D&D Beyond uses this one:
https://www.dndbeyond.com/characters/classes/blood-hunter
which grants the Blood Curses at levels 2 and 5, rather than granting two of them at level 6.

We're getting ready to start a level 5 campaign, and I was interested in this class. I use Hero Lab for as much as possible when it comes to character creation, and wanted to for this, too.

Is there any chance of this being resolved at some point? And, if not, is there any particular reason why?

Thanks again for your time and efforts.

**Comment by Sklore** [comment]
We havn't touched that in over a year. Possibly more. None of us use it which would be why it's not been updated. There's only 1.5 of us maintaining this and our focus is very much on the official content as that's what we use. 

Can absolutely do with more volunteers to help out. I'll add this to my To Do list but thats a long list.

**Comment by kakitahero** [comment]
I'd be interested in helping. The only complication is time to do so. Between working full time and parenting even-fuller-time, free time is more of a memory than a commodity. That said, what sort of help are you in need of, and what sort of slack can I pick up to help you guys focus on more significant work?

**Comment by Sklore** [comment]
I like the sound of that @dungeonguru. There's stuff in here that is likely not being used. @shadowchemosh what's your experience with this sort of thing over in the PF circle?

Now that there is a lot more official content out there I don't think we need to be supporting UA to be honest. It used to be favourable because it was the best way to increase the available options but much of it is now official. 

Personally I'm happy to avoid HB almost completely, Bloodhunter and Gunslinger should probably stay since they aren't really considered HB by most of the community. 

We do make heavy use of the Book of Lost Spells and The (Not Really) Complete Tome of Spells but spells don't require any scripting so they are easy to maintain. 

@grandchefpanda @TheEnthusiast @xdy @DarkHayZe @HippyCraig @LordMorin @BoomerET 
Any of you guys want to weigh in here?

**Comment by dungeonguru** [comment]
Hmm, my vote is to discontinue the homebrew and most 3PP support then. 

I still think we should look to dndbeyond as our compass/guide. That means Blood Hunter and the Tortle package are in, and we only support UA articles that were published after August 2017 (at this point). I would treat the Eberron stuff as though it were a UA article since we know it's bound to make it into a hardback in a year or so. 

For the old stuff, we might have to hide some sources and create new ones to push all the homebrew/retired materials together, I don't think that will be the worst work - just have to make sure there aren't any oddball precludes or hides in the old stuff. 

I don't mind throwing in some 3PP support for materials that will only have occasional errata - like Book of Lost Spells and Fifth Edition Foes from Frog God - if the publishers are OK with a 10% rule or something.

**Comment by dungeonguru** [comment]
**Question** - does anyone on this thread know why Rage of Demons and Tyranny of Dragons have Adventurer's League sources and in the case of Rage of Demons, some monsters? 

**Also**, I have a new Configure Hero menu setup that I'm proposing to push out if we decide to push the older articles to an unsupported legacy - you can download the branch  dungeonguru-08012018-index-fixes and see if that looks like something we'd want to move to.

**Comment by LordMorin** [comment]
Question - does anyone on this thread know why Rage of Demons and Tyranny of Dragons have Adventurer's League sources and in the case of Rage of Demons, some monsters?
I think Adventurer's League put out the player only material in a separate supplement so the players wouldn't have to buy the module just to get access to the player material.

**Comment by TheEnthusiast** [comment]
The League restricts players to PHB+1 sourcebook as a way to curb munchkins.

Enviado de meu ASUS

-------- Mensagem Original --------
De:LordMorin <notifications@github.com>
Enviado em:Tue, 31 Jul 2018 21:38:06 -0300
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:TheEnthusiast <ps3nerobr@gmail.com>,Mention <mention@noreply.github.com>
Assunto:Re: [Sklore/HL_DD_5e_Colab] Blood Hunter Version Outdated? (#859)

**Comment by Enforcer84** [comment]
I started...but petered out...on a Blood Hunter rehash that used configurables like Barbarians. I got as far as Order of the Lycan and Ghostslayer.

I haven't done the Mutant and only have a vague idea how the Profane Soul. (also I use my own labeling etc....but I'd be willing to throw down what I have now. (Actually I posted my taldorei files on the 5e Board.

**Comment by Fenris447** [comment]
The Blood Hunter was updated on DMsGuild in January 2020, so the version in the 5e Community Pack is very much out of date. With nobody actively working on it or requesting it, I’m closing the issues related to this homebrew class. If someone wishes to do the work to fully update it, feel free to open a new ticket.
