### ISSUE TITLE
Changeling Race isn't Up-to-Date

### ISSUE THREAD

**Issue by DjinnMartini** [Sklore/HL_DD_5e_Colab#878]
The changeling player race isn't up-to-date with the most recent version of it, as described here:

https://www.dndbeyond.com/characters/races/changeling

**Comment by LordMorin** [comment]
The changeling you are talking about is from the Wayfinder's Guide to Eberron. Due to lack of scripters, and my own ill health, WGtE hasn't been added the the Community Pack as of yet,

I have the races complete , in a fast and dirty method, for my own Eberron campaign, but have yet to be able to change all the text to comply with Copyright.

It's been my plan to upload what I have when I can, I just haven't been able to get the work done to make it community pack compliant as of yet.

**Comment by DjinnMartini** [comment]
Wow, amazingly fast response! And here I was just thinking I'd note it here. :)

Thanks for your work!

**Comment by LordMorin** [comment]
I am way behind on my promises for the Community Pack. I still have stuff to complete for MToF also . . . :(
