### ISSUE TITLE
UA: Three Subclasses

### ISSUE THREAD

**Issue by Jaxseven** [Sklore/HL_DD_5e_Colab#888]
I've been trying to make the switch to Linux and was trying to make my character sheet on Hero Lab, but since I use a lot of Unearthed Arcana it's been difficult. The only thing I need is the [Brute Fighter Subclass from the "Three Subclasses" UA](https://media.wizards.com/2018/dnd/downloads/UA-3Subclasses0108.pdf). I've checked through all the UA added in the community pack but haven't seen it. I'm new to Hero Lab so I don't know where to start making a subclass.

**Comment by Fenris447** [comment]
I took a look at the subclass and it looks like a pretty easy modification of the Champion. I’ll give it a go soon and upload a workable .user file for you. It won’t be polished like the rest of the Community Pack, but it’ll get you where you’re looking to go.

**Comment by Fenris447** [comment]
Quick and dirty, but it should do. My only real problem is that if you have other abilities or weapons with extra damage added on, they may either overwrite or be overwritten by the Brute Force dice. But absent things like that, the dice will always show on the weapons in their column.

The .user file inside the .zip just goes in your 5e file with all the other .user files from the Community Pack.

[Brute.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/2911886/Brute.zip)
