### ISSUE TITLE
It's been more than a year since a production release

### ISSUE THREAD

**Issue by mmroden** [Sklore/HL_DD_5e_Colab#889]
Hi-- it's been more than a year since a production release.  Do you guys need help crossing the t's and dotting the i's on the work that's been done?  I've seen merge requests have happened in the last year, but nothing that's made it to the regular deployment site as per the instructions in the hero lab community forum.  The most recent version here is 2.1, while 2.2 is what's available for download.  Or am I looking in the wrong place?

Thanks!
Mark

**Comment by dungeonguru** [comment]
Most of the pending changes should be documented on https://github.com/Sklore/HL_DD_5e_Colab/wiki/3.-Pending-Changes ,  but I don't think anyone has been actively keeping up with it since I last updated it to **v2.3** as pending in July last year. I just merged in the pending changes that LordMorin put in for Wayfarer's pull request so SOMEONE needs to test with a fresh download and sign off on it before trying to follow the instructions for a new release and update that wiki page. I'm out of the release business and not supporting the 5e HLC data files anymore so someone needs to step up and help daplunk keep the community alive for you folks.

**Comment by LordMorin** [comment]
My WGtE stuff is not yet complete unfortunately.

**Comment by mmroden** [comment]
So it sounds like you need help @Sklore?  What would that look like?

**Comment by johntoups** [comment]
I am happy to author in fluff content, do you have guidelines or a PR process?  Also happy to QA, assuming I can get a list of changes and can import directly into HL to run the tests...

**Comment by Sklore** [comment]
@mmroden The MTOF is still sitting there needing finishing. I did the grunt work and got the monsters made. But I parsed them in and was unable to do any of the special abilities or actions. Those need to be completed. We made tutorials on how to do this but the uplift from the community was next to none. 

Life got in my way. So if anyone wants to help then this is a great place to start. 

Tracking Issue: https://github.com/Sklore/HL_DD_5e_Colab/issues/834

Tutorials: https://github.com/Sklore/HL_DD_5e_Colab/wiki/Monster
