### ISSUE TITLE
Working on TNRCToS

### ISSUE THREAD

**Issue by HippyCraig** [Sklore/HL_DD_5e_Colab#96]
Updating Class Tages for all spells.  Please refrain from others updating this file.

**Comment by Sklore** [comment]
:+1:

**Comment by shadowchemosh** [comment]
This must be the difference of SourceTree also.  If I was to change the file above and you had changed it in main.  When I did my pull down SourceTree "mod Marks" both sets of changes if we touched the "exact" same lines of code.  In which case I would need to go in manually correct the source code (ie decide which "change" to keep) and then I could push the merged version back to GitHub.

If my changes did NOT in any way conflict with your changes then SourceTree would merge the files for me on the 'Pull'.  And I could simply "push" the merged version back to github with a Commit.

The idea behind a repository is that multiple people can make changes to the same file at the same time.  As long as its different sections of code.

Just some FYI is all. =)

**Comment by shadowchemosh** [comment]
P.S. - I wont' change the file. =)

**Comment by HippyCraig** [comment]
I am aware of how source control works, I put this in so that double work wasn't being done.  Its tedious to add classes to each spell and very time consuming.  It would be shame if two or more people were going through the exercise, it seemed like the best way to communicate to the team what I was doing so there efforts can be best used to something else.

**Comment by HippyCraig** [comment]
Sorry if that came across rude that wasn't my intent.  =)

**Comment by shadowchemosh** [comment]
Oh.  See how bad "text" is at communicating.  I thought you where saying "don't" update because when using Branches in GitHub it seems to like to overwrite file changes.  Sklore already did this once wiping out all my changes/fixes I had done to the Backgrounds tab. =)

So I was just mention that using SourceTree GUI app does not seem to cause that same issue about files getting wiped or misplaced.  That was all my comment was about.

I am sorry also I was in now way attempting to say what anyone did or did not know.  I just like to give information to make sure everyone is on the same page about stuff.

No harm or foul either way HippyCraig.  Unless you swear at me I do my best to take comments as "non-aggressive" =)

**Comment by HippyCraig** [comment]
No Worries, all good.  My first post in this thread really didn't make much sense.  I should have elaborated on my intent in the beginning.

**Comment by HippyCraig** [comment]
Current Status all Spell Class Tags have been updated, half way through reformatting description Text.

**Comment by Sklore** [comment]
Damn mate absolute effort well done

**Comment by HippyCraig** [comment]
Work is completed to DEV branch and a pull request was submitted and committed as well.
